import { EXTRA } from "./extra-events.js";
import { FILL } from "./fill-events.js";
import { hasShort } from "./shorts.js";

/** Curated "On this day" ripples — British, irreverent, channel-shaped. */
export const ERAS = [
  { id: "all", label: "All ripples" },
  { id: "romans", label: "Romans" },
  { id: "tudors", label: "Tudors" },
  { id: "civil-war", label: "Civil Wars" },
  { id: "british", label: "Britain" },
  { id: "ww2", label: "World Wars" },
  { id: "world", label: "Wider world" },
];

export const EVENTS = [
  { m: 1, d: 1, y: 1801, title: "United Kingdom, officially", era: "british", loc: "Westminster", blurb: "The Act of Union takes effect. England, Scotland and Ireland are now one awkward household — with the wallpaper still arguing." },
  { m: 1, d: 1, y: 45, title: "Caesar’s new year", era: "romans", loc: "Rome", blurb: "The Julian calendar begins. January finally means January, give or take a leap year and two thousand years of people getting it wrong." },
  { m: 1, d: 2, y: 1492, title: "Granada falls", era: "world", loc: "Granada", blurb: "The last Muslim emirate in Spain surrenders. Ferdinand and Isabella get the keys; Columbus is already hovering with a business plan." },
  { m: 1, d: 3, y: 1521, title: "Luther, officially cancelled", era: "world", loc: "Rome", blurb: "Pope Leo X excommunicates Martin Luther. The Reformation does not, as hoped, quietly go away." },
  { m: 1, d: 4, y: 1642, title: "Charles tries to nick five MPs", era: "civil-war", loc: "Westminster", blurb: "Charles I marches into the Commons. The birds have flown. Civil war, at this point, is less a possibility than a diary appointment." },
  { m: 1, d: 5, y: 1066, title: "The Confessor dies", era: "british", loc: "Westminster", blurb: "Edward the Confessor shuffles off, leaving a throne, a promise or three, and the most overbooked year in English history." },
  { m: 1, d: 6, y: 1066, title: "Harold takes the crown", era: "british", loc: "Westminster", blurb: "Harold Godwinson is crowned the day after Edward dies. Speed, in 1066, is a survival tactic. It does not last the year." },
  { m: 1, d: 7, y: 1610, title: "Galileo finds company", era: "world", loc: "Padua", blurb: "Jupiter’s moons are spotted. The universe, inconveniently, does not revolve around us. Rome will need a minute." },
  { m: 1, d: 8, y: 1642, title: "Galileo dies", era: "world", loc: "Arcetri", blurb: "The man who made the heavens move is gone. The Earth, despite official policy, keeps going round the Sun." },
  { m: 1, d: 9, y: 1806, title: "Nelson’s funeral", era: "british", loc: "St Paul’s", blurb: "London buries the victor of Trafalgar. The navy weeps. The French, for once, stay quiet." },
  { m: 1, d: 10, y: -49, title: "The Rubicon", era: "romans", loc: "Northern Italy", blurb: "Caesar crosses a modest river and a very large line. ‘The die is cast,’ he says, which is Roman for ‘too late to pretend this was a walking holiday.’" },
  { m: 1, d: 11, y: 630, title: "Mecca falls to Muhammad", era: "world", loc: "Mecca", blurb: "The city opens its gates. A new religious and political order walks in — and does not walk out again." },
  { m: 1, d: 12, y: 1863, title: "The wounded at Stones River", era: "civil-war", loc: "Tennessee", blurb: "One of the American Civil War’s ugliest New Year battles finally gutters out. Nobody writes a catchy poem about this one." },
  { m: 1, d: 13, y: 1898, title: "J’Accuse", era: "world", loc: "Paris", blurb: "Émile Zola detonates the Dreyfus Affair on the front page. France discovers that a miscarriage of justice, once printed, does not stay in the barracks." },
  { m: 1, d: 14, y: 1858, title: "Orsini bombs Napoleon III", era: "world", loc: "Paris", blurb: "An assassination attempt outside the opera. The emperor survives; Italian nationalism gets a darker headline." },
  { m: 1, d: 15, y: 1559, title: "Elizabeth crowned", era: "tudors", loc: "Westminster Abbey", blurb: "The last Tudor takes the crown. England gets a long reign, a navy, a golden age, and absolutely no legitimate heir. Details." },
  { m: 1, d: 16, y: 27, title: "Augustus, in so many words", era: "romans", loc: "Rome", blurb: "The Senate hands Octavian the title Augustus. The Republic is still officially a republic. Nobody is fooled." },
  { m: 1, d: 17, y: 1773, title: "Cook crosses the Antarctic Circle", era: "british", loc: "Southern Ocean", blurb: "Captain Cook takes HMS Resolution where maps turn white. The penguins are not consulted." },
  { m: 1, d: 18, y: 1871, title: "A German empire, in a French palace", era: "world", loc: "Versailles", blurb: "Wilhelm I is proclaimed Kaiser in the Hall of Mirrors. France takes notes. 1914 will be the exam." },
  { m: 1, d: 19, y: 1915, title: "The first Zeppelin raid on Britain", era: "ww2", loc: "Great Yarmouth", blurb: "German airships bomb the home front. The war, previously a Channel away, is suddenly in the parlour." },
  { m: 1, d: 20, y: 1649, title: "The king in the dock", era: "civil-war", loc: "Westminster Hall", blurb: "Charles I’s trial begins. He refuses to recognise the court. The court, unimpressed, recognises him anyway." },
  { m: 1, d: 21, y: 1793, title: "Louis XVI, shortened", era: "world", loc: "Paris", blurb: "The guillotine does in ten seconds what centuries of Bourbon rule could not: make monarchy look suddenly optional." },
  { m: 1, d: 22, y: 1901, title: "Victoria is gone", era: "british", loc: "Osborne House", blurb: "The Queen-Empress dies after 63 years. An age named after her has the good manners to end on cue." },
  { m: 1, d: 23, y: 1570, title: "Elizabeth I excommunicated", era: "tudors", loc: "Rome", blurb: "Pope Pius V declares the English queen a heretic. English Catholics are invited to a very awkward loyalty test." },
  { m: 1, d: 24, y: 41, title: "Caligula, cancelled with extreme prejudice", era: "romans", loc: "Rome", blurb: "The Praetorian Guard murder the emperor. His horse is not, sadly, promoted in the reshuffle." },
  { m: 1, d: 25, y: 1533, title: "Henry marries Anne, quietly", era: "tudors", loc: "Whitehall", blurb: "A secret wedding, a very public schism. Rome is not on the guest list." },
  { m: 1, d: 26, y: 1788, title: "The First Fleet", era: "british", loc: "Sydney Cove", blurb: "Britain plants a flag and a penal colony. Australia will have thoughts about this later." },
  { m: 1, d: 27, y: 1945, title: "Auschwitz liberated", era: "ww2", loc: "Poland", blurb: "The Red Army walks into the camp. The century has to look at itself. Holocaust Memorial Day is kept here for a reason." },
  { m: 1, d: 28, y: 1547, title: "Henry VIII dies", era: "tudors", loc: "Whitehall", blurb: "Six wives, one Reformation, and a waistline that needed its own postcode. The boy-king Edward VI inherits the lot." },
  { m: 1, d: 29, y: 1820, title: "George III dies", era: "british", loc: "Windsor", blurb: "Sixty years of reign, a lost America, and a mind that wandered. The Regency can stop pretending." },
  { m: 1, d: 30, y: 1649, title: "Charles I executed", era: "civil-war", loc: "Whitehall", blurb: "A king of England loses his head on a cold Tuesday. Divine right, it turns out, is negotiable." },
  { m: 1, d: 31, y: 1606, title: "Guy Fawkes executed", era: "british", loc: "Westminster", blurb: "The Gunpowder Plot’s most famous face meets the scaffold. Bonfire Night will be funnier than this morning." },

  { m: 2, d: 1, y: 1943, title: "Stalingrad, over", era: "ww2", loc: "Stalingrad", blurb: "Field Marshal Paulus surrenders. Hitler had promoted him so he wouldn’t. The Eastern Front does not take hints." },
  { m: 2, d: 2, y: 1461, title: "Battle of Mortimer’s Cross", era: "british", loc: "Herefordshire", blurb: "York beats Lancaster under a parhelion — three suns in the sky. Edward takes it as a good review. The Wars of the Roses continue anyway." },
  { m: 2, d: 3, y: 1461, title: "Battle of the Second St Albans", era: "british", loc: "Hertfordshire", blurb: "Margaret of Anjou’s Lancastrians win the town back. The Wars of the Roses remain, as ever, terrible for property prices." },
  { m: 2, d: 4, y: 211, title: "Septimius Severus dies at York", era: "romans", loc: "Eboracum", blurb: "An African-born emperor dies on the Wall’s doorstep, telling his sons to agree. They do not." },
  { m: 2, d: 5, y: 1818, title: "Bernadotte, King of Sweden", era: "world", loc: "Stockholm", blurb: "Napoleon’s old marshal gets a crown. France loses a general; Sweden gains a dynasty that is still there." },
  { m: 2, d: 6, y: 1952, title: "George VI dies", era: "british", loc: "Sandringham", blurb: "Elizabeth is in Kenya. By the time the news reaches her, she is already Queen. The second Elizabethan age starts in a treehouse, more or less." },
  { m: 2, d: 7, y: 1812, title: "Dickens born", era: "british", loc: "Portsmouth", blurb: "The man who will invent Christmas, fog, and half of London’s guilt arrives in a naval town." },
  { m: 2, d: 8, y: 1587, title: "Mary, Queen of Scots, executed", era: "tudors", loc: "Fotheringhay", blurb: "Elizabeth signs, then pretends she didn’t mean it. Mary’s dog is found under her skirts. The whole business is as ugly as it is necessary." },
  { m: 2, d: 9, y: 1942, title: "French liners burned at New York", era: "ww2", loc: "New York", blurb: "The Normandie catches fire while being converted for war. Luxury, meet the twentieth century." },
  { m: 2, d: 10, y: 1840, title: "Victoria marries Albert", era: "british", loc: "St James’s", blurb: "A love match, a German prince, and the template for every royal wedding since. The moustache does a surprising amount of work." },
  { m: 2, d: 11, y: 1990, title: "Mandela walks free", era: "world", loc: "Cape Town", blurb: "Twenty-seven years end on a dusty road. Apartheid has not yet fallen. It has, however, started checking the exit signs." },
  { m: 2, d: 12, y: 1554, title: "Lady Jane Grey executed", era: "tudors", loc: "Tower of London", blurb: "The Nine Days’ Queen is seventeen. Mary I does not do half measures, or second chances." },
  { m: 2, d: 13, y: 1689, title: "William and Mary offered the crown", era: "british", loc: "London", blurb: "Parliament shops for a monarch who will read the terms and conditions. The Glorious Revolution gets its new letterhead." },
  { m: 2, d: 14, y: 1929, title: "St Valentine’s Day Massacre", era: "world", loc: "Chicago", blurb: "Capone’s people send flowers of a different sort. Romance, Chicago-style." },
  { m: 2, d: 15, y: 1942, title: "Singapore falls", era: "ww2", loc: "Singapore", blurb: "Churchill’s ‘worst disaster’ of the war. The fortress that couldn’t be taken from the sea is taken from the land. Awkward." },
  { m: 2, d: 16, y: 1804, title: "USS Philadelphia burned", era: "world", loc: "Tripoli", blurb: "Stephen Decatur slips into harbour and torches a captured American frigate. Nelson, watching from a distance, is said to have approved." },
  { m: 2, d: 17, y: 1600, title: "Giordano Bruno burned", era: "world", loc: "Rome", blurb: "An infinite universe is a dangerous idea if you say it in the wrong square. Campo de’ Fiori still remembers." },
  { m: 2, d: 18, y: 1478, title: "The Duke of Clarence, drowned in malmsey", era: "british", loc: "Tower of London", blurb: "George Plantagenet is privately executed. Tradition insists on a barrel of wine. The Wars of the Roses: never knowingly under-catered." },
  { m: 2, d: 19, y: 197, title: "Battle of Lugdunum", era: "romans", loc: "Lyon", blurb: "Severus smashes Clodius Albinus in one of the largest battles Roman ever fought against Roman. The prize is the empire. The bill is Gaul." },
  { m: 2, d: 20, y: 1472, title: "Orkney and Shetland pledged", era: "british", loc: "Scotland", blurb: "A dowry unpaid, islands transferred. Scotland keeps them. Norway will be chasing the receipt for some time." },
  { m: 2, d: 21, y: 1916, title: "Verdun begins", era: "ww2", loc: "Verdun", blurb: "Falkenhayn tries to bleed France white. Ten months later, both sides are the same colour." },
  { m: 2, d: 22, y: 1797, title: "The last invasion of Britain", era: "british", loc: "Fishguard", blurb: "A French force lands in Pembrokeshire and lasts two days. Welsh women in red cloaks are rumoured to have helped with the optics." },
  { m: 2, d: 23, y: 1945, title: "The flag on Iwo Jima", era: "ww2", loc: "Mount Suribachi", blurb: "A photograph that will outlive the battle. The island itself still has a fortnight of dying left." },
  { m: 2, d: 24, y: 1582, title: "Gregory skips ten days", era: "world", loc: "Rome", blurb: "The Gregorian calendar is ordered. Catholic Europe loses a week and a bit. Protestant England sulks about it until 1752." },
  { m: 2, d: 25, y: 1570, title: "Pius V’s bull against Elizabeth", era: "tudors", loc: "Rome", blurb: "Regnans in Excelsis is dated about now in some reckonings — the Pope’s open letter inviting Englishmen to stop obeying their queen. It does not go down well in London." },
  { m: 2, d: 26, y: 1815, title: "Napoleon leaves Elba", era: "world", loc: "Elba", blurb: "The hundred days begin with a small boat and a large ego. Waterloo is already in the diary, it just doesn’t know it." },
  { m: 2, d: 27, y: 1933, title: "The Reichstag burns", era: "ww2", loc: "Berlin", blurb: "A parliament in flames, a chancellor with a shopping list. Emergency powers do the rest." },
  { m: 2, d: 28, y: 202, title: "Perpetua martyred", era: "romans", loc: "Carthage", blurb: "A Roman noblewoman writes her own passion. The arena does not get the last word; the diary does." },
  { m: 2, d: 29, y: 1504, title: "Columbus and the eclipse", era: "world", loc: "Jamaica", blurb: "Stranded, he predicts a lunar eclipse and panics the locals into feeding his crew. Science, used as a dinner reservation." },

  { m: 3, d: 1, y: 1692, title: "Salem’s first arrests", era: "world", loc: "Massachusetts", blurb: "A village decides that teenage panic is admissible evidence. The hangings will follow. The apologies will take rather longer." },
  { m: 3, d: 2, y: 1796, title: "Napoleon given the Army of Italy", era: "world", loc: "Paris", blurb: "A skinny general from Corsica is handed a starving army. Europe is about to need a bigger map." },
  { m: 3, d: 3, y: 1861, title: "Serfdom abolished in Russia", era: "world", loc: "St Petersburg", blurb: "Alexander II frees twenty million people — onto land they still don’t quite own. Reform, with footnotes." },
  { m: 3, d: 4, y: 1461, title: "Edward IV proclaimed", era: "british", loc: "London", blurb: "The Yorkist giant takes the throne. Towton, the bloodbath that will confirm it, is a few weeks away." },
  { m: 3, d: 5, y: 1770, title: "Boston Massacre", era: "world", loc: "Boston", blurb: "Redcoats fire into a crowd. Five dead, one revolution pre-heated. Paul Revere does the engraving." },
  { m: 3, d: 6, y: 1836, title: "The Alamo falls", era: "world", loc: "San Antonio", blurb: "Thirteen days, then a morning. Remembering it becomes the point; surviving it was not an option on offer." },
  { m: 3, d: 7, y: 1876, title: "Bell patents the telephone", era: "world", loc: "United States", blurb: "‘Mr Watson, come here.’ The first words on a device that will never again be that polite." },
  { m: 3, d: 8, y: 1917, title: "International Women’s Day, Petrograd", era: "world", loc: "Petrograd", blurb: "Striking women start the February Revolution (it’s March on the Western calendar; Russia is being difficult). The Tsar has weeks." },
  { m: 3, d: 9, y: 1796, title: "Napoleon marries Josephine", era: "world", loc: "Paris", blurb: "A love letter factory opens. The marriage will not survive the empire. The myth will." },
  { m: 3, d: 10, y: 241, title: "Rome beats Carthage at sea", era: "romans", loc: "Sicily", blurb: "The Battle of the Aegates Islands ends the First Punic War. Rome, previously a land power, has learned to get its feet wet." },
  { m: 3, d: 11, y: 1708, title: "Pretender tries Scotland", era: "british", loc: "Firth of Forth", blurb: "The Old Pretender’s French-backed landing is shooed away. Jacobitism will need a better day. Culloden is still a generation off." },
  { m: 3, d: 12, y: 1938, title: "Anschluss", era: "ww2", loc: "Austria", blurb: "German troops cross the border. Austria becomes a province before lunch. Europe looks at its shoes." },
  { m: 3, d: 13, y: 1881, title: "Alexander II assassinated", era: "world", loc: "St Petersburg", blurb: "The Tsar-Liberator is killed by a bomb. Reform in Russia takes a long holiday." },
  { m: 3, d: 14, y: 44, title: "The Ides, minus one", era: "romans", loc: "Rome", blurb: "Caesar has a day left. The soothsayer has already had his say. Tomorrow’s diary is full." },
  { m: 3, d: 15, y: -44, title: "The Ides of March", era: "romans", loc: "Rome", blurb: "Twenty-three daggers. A republic that thought it was saving itself. Shakespeare does the rewrite; history does the sequel — more emperors." },
  { m: 3, d: 16, y: 1917, title: "The Tsar abdicates", era: "world", loc: "Pskov", blurb: "Nicholas II signs away a dynasty in a railway carriage. The Romanovs have months. Russia has a revolution." },
  { m: 3, d: 17, y: 45, title: "Caesar’s last triumph", era: "romans", loc: "Rome", blurb: "Around now Caesar is still very much alive and very much in charge. The Senate is smiling. Keep an eye on the calendar." },
  { m: 3, d: 18, y: 1314, title: "Jacques de Molay burned", era: "medieval", loc: "Paris", blurb: "The last Templar Grand Master goes to the stake cursing king and pope. Both men are dead within the year. Coincidence is a hell of a brand." },
  { m: 3, d: 19, y: 1649, title: "The House of Lords abolished", era: "civil-war", loc: "Westminster", blurb: "The Commonwealth decides it does not need ermine. It will, of course, be back. Everything in English politics is back." },
  { m: 3, d: 20, y: 1602, title: "The Dutch East India Company", era: "world", loc: "Amsterdam", blurb: "The VOC is chartered. Capitalism gets a fleet, a monopoly, and a body count." },
  { m: 3, d: 21, y: 1801, title: "Battle of Alexandria", era: "british", loc: "Egypt", blurb: "Abercromby beats the French and is mortally wounded doing it. The Nile campaign gets its land-based epilogue." },
  { m: 3, d: 22, y: 1622, title: "Jamestown massacre", era: "world", loc: "Virginia", blurb: "Powhatan fighters strike the colony. The English lesson taken is the wrong one, at length." },
  { m: 3, d: 23, y: 1801, title: "Tsar Paul I murdered", era: "world", loc: "St Petersburg", blurb: "A palace coup in a dressing gown. Alexander I inherits, and will later meet Napoleon in a raft on a river, because the nineteenth century is like that." },
  { m: 3, d: 24, y: 1603, title: "Elizabeth I dies", era: "tudors", loc: "Richmond", blurb: "The last Tudor goes quietly. James of Scotland rides south. The Jacobean age begins with a new accent and the same throne." },
  { m: 3, d: 25, y: 1306, title: "Robert the Bruce crowned", era: "british", loc: "Scone", blurb: "Scotland gets a king who will refuse to stay beaten. Bannockburn is eight years and a lot of running away from here." },
  { m: 3, d: 26, y: 1830, title: "The Book of Mormon published", era: "world", loc: "New York", blurb: "A new American scripture leaves the press. The frontier is about to get a religion to match it." },
  { m: 3, d: 27, y: 1964, title: "Good Friday earthquake", era: "world", loc: "Alaska", blurb: "The most powerful quake in American history. Anchorage learns what the Pacific Rim actually means." },
  { m: 3, d: 28, y: 1939, title: "Madrid falls", era: "world", loc: "Madrid", blurb: "The Spanish Civil War is effectively over. Franco has decades. Spain has a long silence." },
  { m: 3, d: 29, y: 1461, title: "Towton", era: "british", loc: "Yorkshire", blurb: "Palm Sunday, a snowstorm, and perhaps the bloodiest battle ever fought on English soil. Edward IV’s throne is paid for in full." },
  { m: 3, d: 30, y: 1867, title: "Seward’s Icebox", era: "world", loc: "Washington", blurb: "The US buys Alaska from Russia. Everyone laughs. Then they find the gold. Then the oil. The laugh gets quieter." },
  { m: 3, d: 31, y: 1889, title: "The Eiffel Tower opens", era: "world", loc: "Paris", blurb: "Parisians call it a lamppost. It stays. Most lampposts do not get 130 years of postcards." },

  { m: 4, d: 1, y: 1918, title: "The RAF is born", era: "ww2", loc: "United Kingdom", blurb: "The world’s first independent air force. A month after its birthday it will be fighting for its life. The Few are still schoolboys." },
  { m: 4, d: 2, y: 1982, title: "Argentina invades the Falklands", era: "british", loc: "Port Stanley", blurb: "A Thursday morning in the South Atlantic. Britain discovers it still has a navy, and a temper." },
  { m: 4, d: 3, y: 1721, title: "Walpole, first among ministers", era: "british", loc: "Westminster", blurb: "Robert Walpole becomes the thing we will later call Prime Minister. The title is unofficial. The power is not." },
  { m: 4, d: 4, y: 1968, title: "Martin Luther King assassinated", era: "world", loc: "Memphis", blurb: "A balcony, a rifle, and a movement that has to keep walking without its voice." },
  { m: 4, d: 5, y: 1614, title: "Pocahontas marries John Rolfe", era: "world", loc: "Jamestown", blurb: "A diplomatic marriage in Virginia. Disney will later have notes. History prefers tobacco." },
  { m: 4, d: 6, y: 1199, title: "Richard the Lionheart wounded", era: "british", loc: "Châlus", blurb: "A crossbow bolt in the shoulder at a minor siege. The king who could not sit still in England will die of this in ten days." },
  { m: 4, d: 7, y: 451, title: "Attila in Gaul", era: "world", loc: "Western Empire", blurb: "The Hunnic invasion season opens. The Catalaunian Plains will be the sequel. Rome, as usual, is late with the script." },
  { m: 4, d: 8, y: 1820, title: "The Venus de Milo found", era: "world", loc: "Milos", blurb: "A farmer finds a goddess without arms. The Louvre gets a star. Art history gets an argument." },
  { m: 4, d: 9, y: 1865, title: "Appomattox", era: "civil-war", loc: "Virginia", blurb: "Lee surrenders to Grant. The courthouse belongs to the same man who owned the farm at Bull Run, where the whole mess started. History, never knowingly understated.", video: "H2BnvEUAvSU" },
  { m: 4, d: 10, y: 1912, title: "Titanic leaves Southampton", era: "british", loc: "Southampton", blurb: "Unsinkable, they said. The iceberg has not been copied in on the press release." },
  { m: 4, d: 11, y: 1814, title: "Napoleon abdicates", era: "world", loc: "Fontainebleau", blurb: "The first time. Elba is the consolation prize. He will treat it as a waiting room." },
  { m: 4, d: 12, y: 1861, title: "Fort Sumter fired on", era: "civil-war", loc: "Charleston", blurb: "The American Civil War begins with a bombardment and no fatalities. That statistic will not last." },
  { m: 4, d: 13, y: 1598, title: "The Edict of Nantes", era: "world", loc: "France", blurb: "Henri IV tries to stop Frenchmen murdering Frenchmen over God. It works, until a later Louis revokes it." },
  { m: 4, d: 14, y: 1865, title: "Lincoln shot", era: "civil-war", loc: "Washington", blurb: "Ford’s Theatre, a box, a broken country trying to heal. Reconstruction will now be done by other hands." },
  { m: 4, d: 15, y: 1912, title: "Titanic goes down", era: "british", loc: "North Atlantic", blurb: "2:20 a.m. The band, the boats, the water. A floating hotel becomes a parable in two hours." },
  { m: 4, d: 16, y: 1746, title: "Culloden", era: "british", loc: "Inverness", blurb: "Forty minutes on a moor. The Jacobite cause is finished, the Highlands will be punished, and Bonnie Prince Charlie will become a shortbread tin." },
  { m: 4, d: 17, y: 1961, title: "Bay of Pigs", era: "world", loc: "Cuba", blurb: "An invasion that lasts three days and a reputation that lasts rather longer. Kennedy learns about deniability the hard way." },
  { m: 4, d: 18, y: 1775, title: "Paul Revere’s ride", era: "world", loc: "Massachusetts", blurb: "The regulars are out. Lexington Green is a few hours away. American independence starts as a night alarm." },
  { m: 4, d: 19, y: 1775, title: "Lexington and Concord", era: "world", loc: "Massachusetts", blurb: "The shot heard round the world — or at least round a village green. Empires, it turns out, can lose to militias who know the lanes." },
  { m: 4, d: 20, y: 1653, title: "Cromwell dissolves the Rump", era: "civil-war", loc: "Westminster", blurb: "‘In the name of God, go.’ The army sends Parliament home. Republics, English-style, have a short temper." },
  { m: 4, d: 21, y: 753, title: "Rome founded, allegedly", era: "romans", loc: "Rome", blurb: "Varro’s date for Romulus and the wolf. Archaeology has notes. The brand is unbeatable." },
  { m: 4, d: 22, y: 1500, title: "Cabral sights Brazil", era: "world", loc: "South America", blurb: "Portugal, aiming for India, collects a continent by accident. The Treaty of Tordesillas had, in fairness, drawn a line for this." },
  { m: 4, d: 23, y: 1564, title: "Shakespeare born — probably", era: "tudors", loc: "Stratford-upon-Avon", blurb: "Baptised the 26th, tradition gives him today, St George’s Day. England’s other patron saint of leaving it late and still being brilliant." },
  { m: 4, d: 24, y: 1916, title: "Easter Rising begins", era: "british", loc: "Dublin", blurb: "A week that fails as a revolt and succeeds as a founding myth. The executions will do the recruiting." },
  { m: 4, d: 25, y: 1859, title: "Work starts on Suez", era: "world", loc: "Egypt", blurb: "De Lesseps turns a shovel. The Mediterranean and the Red Sea will eventually shake hands. Britain will want a word about the shareholding." },
  { m: 4, d: 26, y: 1937, title: "Guernica", era: "ww2", loc: "Basque Country", blurb: "The Luftwaffe practises on a market town. Picasso does the painting. Europe gets the preview." },
  { m: 4, d: 27, y: 1521, title: "Magellan killed", era: "world", loc: "Mactan", blurb: "The circumnavigation continues without its captain. Local politics, as ever, was not on the chart." },
  { m: 4, d: 28, y: 1789, title: "The Bounty mutiny", era: "british", loc: "South Pacific", blurb: "Bligh is given a boat. Fletcher Christian is given a bad conscience and a South Sea island. The Admiralty is given a very long report." },
  { m: 4, d: 29, y: 1945, title: "Dachau liberated", era: "ww2", loc: "Bavaria", blurb: "American troops walk in. The war in Europe has a week. The evidence does not need a week." },
  { m: 4, d: 30, y: 1945, title: "Hitler dead", era: "ww2", loc: "Berlin", blurb: "A bunker, a marriage, a suicide. The thousand-year Reich manages twelve, and ends in a cellar." },

  { m: 5, d: 1, y: 1707, title: "The Union of England and Scotland", era: "british", loc: "Westminster", blurb: "Two parliaments become one. The arguments do not. They simply get a shared minute book." },
  { m: 5, d: 2, y: 2011, title: "Bin Laden killed", era: "world", loc: "Abbottabad", blurb: "A compound, a raid, a decade-long hunt ended in forty minutes. The war that followed him does not end on the same timetable." },
  { m: 5, d: 3, y: 1808, title: "Madrid’s second of May, the day after", era: "world", loc: "Madrid", blurb: "Goya’s executions of the rebels. Napoleon’s brother is on the Spanish throne. Spain does not take it well." },
  { m: 5, d: 4, y: 1471, title: "Battle of Tewkesbury", era: "british", loc: "Gloucestershire", blurb: "Lancaster’s last throw. The Prince of Wales is killed, Margaret of Anjou is finished, Edward IV is not." },
  { m: 5, d: 5, y: 1821, title: "Napoleon dies on St Helena", era: "world", loc: "St Helena", blurb: "Stomach cancer, or boredom, or both. The man who redrew Europe is buried on a rock. Paris will want the body back." },
  { m: 5, d: 6, y: 1937, title: "Hindenburg burns", era: "world", loc: "New Jersey", blurb: "‘Oh, the humanity.’ Hydrogen, static, and the end of the airship as a serious idea." },
  { m: 5, d: 7, y: 1915, title: "Lusitania sunk", era: "ww2", loc: "Off Ireland", blurb: "A U-boat, a liner, 1,198 dead. America takes a long, hard look at neutrality." },
  { m: 5, d: 8, y: 1945, title: "VE Day", era: "ww2", loc: "Europe", blurb: "The lights go on. Churchill on the balcony, crowds in the fountains, and a war in the Pacific that has not read the memo." },
  { m: 5, d: 9, y: 1671, title: "Colonel Blood steals the Crown Jewels", era: "british", loc: "Tower of London", blurb: "He is caught with the crown under his cloak. Charles II, amused, lets him off. Security reviews are invented shortly afterwards." },
  { m: 5, d: 10, y: 1940, title: "Churchill becomes PM", era: "ww2", loc: "Downing Street", blurb: "Germany invades the West the same day. The job interview is the job. ‘I have nothing to offer but blood, toil, tears and sweat.’" },
  { m: 5, d: 11, y: 1812, title: "Spencer Perceval assassinated", era: "british", loc: "Westminster", blurb: "The only British PM to be shot in the lobby. The killer had a grievance about pay. Parliament, for once, is not bored." },
  { m: 5, d: 12, y: 1949, title: "Berlin Blockade ends", era: "ww2", loc: "Berlin", blurb: "The airlift has fed a city for eleven months. Stalin blinks. The Cold War has found its tone." },
  { m: 5, d: 13, y: 1940, title: "Blood, toil, tears and sweat", era: "ww2", loc: "Commons", blurb: "Churchill’s first speech as PM. The rhetoric department is open. The army is still in France, for now." },
  { m: 5, d: 14, y: 1264, title: "Battle of Lewes", era: "british", loc: "Sussex", blurb: "Simon de Montfort captures Henry III. Parliament gets an early, unofficial dress rehearsal. The South Downs do the rest." },
  { m: 5, d: 15, y: 1648, title: "The Treaty of Westphalia, brewing", era: "world", loc: "Münster", blurb: "Talks that will end the Thirty Years’ War are grinding on. Europe is inventing the nation-state, mostly by being exhausted." },
  { m: 5, d: 16, y: 1770, title: "Marie Antoinette marries the future Louis XVI", era: "world", loc: "Versailles", blurb: "A teenage Austrian in French silk. The cake, contrary to later branding, is not yet a talking point." },
  { m: 5, d: 17, y: 1900, title: "Mafeking relieved", era: "british", loc: "South Africa", blurb: "Baden-Powell becomes a household name. London goes briefly mad. The Boer War is not, in fact, over." },
  { m: 5, d: 18, y: 1804, title: "Napoleon becomes Emperor", era: "world", loc: "Paris", blurb: "The Republic crowns a Caesar. Beethoven scratches out a dedication. Europe reaches for its coalitions." },
  { m: 5, d: 19, y: 1536, title: "Anne Boleyn executed", era: "tudors", loc: "Tower Green", blurb: "A French swordsman, a trumped-up charge, a king already betrothed to the next one. The Reformation keeps its cruel timetable." },
  { m: 5, d: 20, y: 1498, title: "Vasco da Gama reaches India", era: "world", loc: "Calicut", blurb: "The Cape is rounded, the ocean is a Portuguese road, and Venice’s spice monopoly is about to have a terrible century." },
  { m: 5, d: 21, y: 1927, title: "Lindbergh lands in Paris", era: "world", loc: "Le Bourget", blurb: "Thirty-three hours alone over the Atlantic. The modern celebrity is born in a leather jacket." },
  { m: 5, d: 22, y: 1455, title: "First Battle of St Albans", era: "british", loc: "Hertfordshire", blurb: "The Wars of the Roses open in a high street. York wins. England has thirty years of this to look forward to." },
  { m: 5, d: 23, y: 1701, title: "Captain Kidd hanged", era: "british", loc: "Wapping", blurb: "Pirate, privateer, scapegoat — pick one. His body hangs in the Thames as a notice to shipping." },
  { m: 5, d: 24, y: 1819, title: "Victoria born", era: "british", loc: "Kensington Palace", blurb: "A small princess who was not supposed to reign. She will give her name to an age, an empire, and a lot of railway stations." },
  { m: 5, d: 25, y: 1659, title: "Richard Cromwell resigns", era: "civil-war", loc: "England", blurb: "Tumbledown Dick cannot fill the father’s boots. The Restoration is now a matter of when, not if." },
  { m: 5, d: 26, y: 1805, title: "Napoleon crowned in Italy", era: "world", loc: "Milan", blurb: "A second crown, an Iron Crown of Lombardy. The man collects kingdoms the way other people collect stamps." },
  { m: 5, d: 27, y: 1941, title: "Bismarck sunk", era: "ww2", loc: "North Atlantic", blurb: "The pride of the Kriegsmarine is hunted down. Hood is already avenged. The Atlantic, slightly, belongs to the Admiralty again." },
  { m: 5, d: 28, y: 1967, title: "Francis Chichester home", era: "british", loc: "Plymouth", blurb: "Around the world, alone, in a small boat. Elizabeth knights him with Drake’s sword, because some traditions still work." },
  { m: 5, d: 29, y: 1453, title: "Constantinople falls", era: "world", loc: "Constantinople", blurb: "The last Roman emperor dies in the breach. The Ottomans take the city. The Middle Ages, depending on who you ask, get an end date." },
  { m: 5, d: 30, y: 1431, title: "Joan of Arc burned", era: "world", loc: "Rouen", blurb: "Nineteen, a heretic on paper, a saint in waiting. The English do the fire; the French do the memory." },
  { m: 5, d: 31, y: 1916, title: "Jutland", era: "ww2", loc: "North Sea", blurb: "The only full-dress clash of dreadnoughts. Both sides claim it. The German fleet stays in port afterwards, which is a kind of answer." },

  { m: 6, d: 1, y: 1939, title: "The submarine Thetis sinks", era: "british", loc: "Liverpool Bay", blurb: "A Royal Navy disaster in sight of land. Ninety-nine men. The sea, as ever, does not do dress rehearsals." },
  { m: 6, d: 2, y: 1953, title: "The Coronation", era: "british", loc: "Westminster Abbey", blurb: "Elizabeth II crowned on television. The country buys sets, holds street parties, and pretends the rain is part of the pageant." },
  { m: 6, d: 3, y: 1940, title: "Dunkirk, last full day", era: "ww2", loc: "Dunkirk", blurb: "The little ships have done the impossible. The army is home, without its guns. Churchill is already writing the speech for tomorrow." },
  { m: 6, d: 4, y: 1940, title: "We shall fight on the beaches", era: "ww2", loc: "Commons", blurb: "Dunkirk is over; the sentence is not. Churchill tells the House — and Hitler — that this island is not in the market.", video: "30oVQx89fHk" },
  { m: 6, d: 5, y: 1968, title: "Robert Kennedy shot", era: "world", loc: "Los Angeles", blurb: "A hotel kitchen, a year of assassinations. He dies the next day. America keeps burying its alternatives." },
  { m: 6, d: 6, y: 1944, title: "D-Day", era: "ww2", loc: "Normandy", blurb: "The largest seaborne invasion in history. Lord Lovat and piper Bill Millin walk up Sword Beach as if it were a Highland road. The plan holds. Just.", video: "g2X5MubKN4s" },
  { m: 6, d: 7, y: 1099, title: "Crusaders reach Jerusalem", era: "world", loc: "Jerusalem", blurb: "The First Crusade arrives in the heat. In a month the city will fall, and the chroniclers will not spare us the details." },
  { m: 6, d: 8, y: 793, title: "Lindisfarne raided", era: "british", loc: "Northumberland", blurb: "The Vikings announce themselves on a holy island. English history gets a new problem, and a new aesthetic." },
  { m: 6, d: 9, y: 68, title: "Nero dead", era: "romans", loc: "Rome", blurb: "The last Julio-Claudian exits, assisted. The Year of the Four Emperors is now taking bookings." },
  { m: 6, d: 10, y: 1829, title: "The first Oxford-Cambridge Boat Race", era: "british", loc: "Henley", blurb: "Oxford win. A national obsession is accidentally founded. Blazers will never recover." },
  { m: 6, d: 11, y: 1509, title: "Henry VIII marries Catherine of Aragon", era: "tudors", loc: "Greenwich", blurb: "The first wife. The happy years. The future is still a son who will not arrive." },
  { m: 6, d: 12, y: 1942, title: "Anne Frank’s first diary entry", era: "ww2", loc: "Amsterdam", blurb: "A thirteenth birthday present. The annex is still months away. The voice is already there." },
  { m: 6, d: 13, y: 1381, title: "Peasants’ Revolt reaches London", era: "british", loc: "London", blurb: "Wat Tyler’s people are in the capital. A boy-king will talk, a mayor will strike, and the poll tax will not be the last of its kind." },
  { m: 6, d: 14, y: 1645, title: "Naseby", era: "civil-war", loc: "Northamptonshire", blurb: "Fairfax and Cromwell smash the king’s army. The First Civil War is, in all but the paperwork, decided in a Leicestershire field." },
  { m: 6, d: 15, y: 1215, title: "Magna Carta sealed", era: "british", loc: "Runnymede", blurb: "A reluctant John, a meadow, a list of grievances that will be quoted for eight centuries, usually by people who have not read clause 61." },
  { m: 6, d: 16, y: 1487, title: "Stoke Field", era: "british", loc: "Nottinghamshire", blurb: "The last pitched battle of the Wars of the Roses. Lambert Simnel, the fake earl, is pardoned and sent to the kitchens. Henry VII has a sense of humour, of sorts." },
  { m: 6, d: 17, y: 1775, title: "Bunker Hill", era: "world", loc: "Boston", blurb: "The British take the hill and lose the argument. ‘Don’t fire until you see the whites of their eyes’ — cheap ammunition, expensive empire." },
  { m: 6, d: 18, y: 1815, title: "Waterloo", era: "british", loc: "Belgium", blurb: "A long Sunday. Wellington, Blücher, and a ridge. Napoleon’s hundred days end in the mud. The map of Europe is redrawn over dinner.", video: "Qd2rql_TklE" },
  { m: 6, d: 18, y: 1940, title: "Their Finest Hour", era: "ww2", loc: "Commons", blurb: "France is falling. Churchill tells the country that if the British Empire lasts a thousand years, men will still say this was its finest hour. He may be right.", video: "BcU5deW_Nys" },
  { m: 6, d: 19, y: 1865, title: "Juneteenth", era: "civil-war", loc: "Galveston", blurb: "The Emancipation news reaches Texas, two years late. Freedom, like the post, arrives when it arrives." },
  { m: 6, d: 20, y: 1837, title: "Victoria becomes queen", era: "british", loc: "Kensington", blurb: "Eighteen years old, woken at six, in her dressing gown. The nineteenth century now has a name." },
  { m: 6, d: 21, y: 1813, title: "Vitoria", era: "british", loc: "Spain", blurb: "Wellington breaks Joseph Bonaparte’s army. The Peninsular War tilts for good. Napoleon’s brother should have stayed in Naples." },
  { m: 6, d: 22, y: 1941, title: "Barbarossa", era: "ww2", loc: "Soviet Union", blurb: "Hitler invades the USSR. The largest land invasion in history. He has not read his Napoleon." },
  { m: 6, d: 23, y: 1314, title: "Bannockburn, day one", era: "british", loc: "Stirling", blurb: "Edward II’s great host meets Robert the Bruce. Tomorrow will be worse for the English. Scotland is not, it turns out, a weekend job." },
  { m: 6, d: 24, y: 1314, title: "Bannockburn", era: "british", loc: "Stirling", blurb: "Midsummer, a burn, a schiltron. English heavy cavalry discovers Scottish infantry. Independence gets its battle honour." },
  { m: 6, d: 25, y: 1876, title: "Little Bighorn", era: "world", loc: "Montana", blurb: "Custer’s last stand. Sitting Bull and Crazy Horse win a battle and lose the war that follows, because that is how these stories are written." },
  { m: 6, d: 26, y: 1483, title: "Richard III crowned", era: "british", loc: "Westminster", blurb: "The princes are in the Tower. The hunchback of later propaganda puts on the crown. Bosworth is two summers away." },
  { m: 6, d: 27, y: 1954, title: "The first nuclear reactor in the USSR", era: "world", loc: "Obninsk", blurb: "Atoms for peace, in theory. The Cold War now has a new kind of furnace." },
  { m: 6, d: 28, y: 1914, title: "Sarajevo", era: "ww2", loc: "Sarajevo", blurb: "A wrong turn, a sandwich shop, a pistol. Franz Ferdinand dies, and a generation is booked into the trenches." },
  { m: 6, d: 29, y: 1613, title: "The Globe burns", era: "british", loc: "Southwark", blurb: "A cannon in Henry VIII sets the thatch off. Shakespeare’s theatre goes up in an hour. Nobody dies. The play, one assumes, is stopped." },
  { m: 6, d: 30, y: 1934, title: "Night of the Long Knives", era: "ww2", loc: "Germany", blurb: "Hitler murders his own stormtroopers. The army looks the other way. The dictatorship drops the pretence." },

  { m: 7, d: 1, y: 1916, title: "The Somme, first day", era: "ww2", loc: "Picardy", blurb: "57,000 British casualties before tea. The worst day in the history of the British Army. The whistles, the wire, the lesson that isn’t learned." },
  { m: 7, d: 2, y: 1644, title: "Marston Moor", era: "civil-war", loc: "Yorkshire", blurb: "Cromwell’s cavalry wins the north. Prince Rupert’s dog is killed. The king’s cause loses its largest army in an evening." },
  { m: 7, d: 3, y: 1863, title: "Pickett’s Charge", era: "civil-war", loc: "Gettysburg", blurb: "The high-water mark of the Confederacy is a walk across an open field. It does not go well." },
  { m: 7, d: 4, y: 1776, title: "Independence declared", era: "world", loc: "Philadelphia", blurb: "Jefferson’s sentences, a vote, a bell that may or may not have rung. Britain has lost a set of colonies and gained a rival." },
  { m: 7, d: 5, y: 1945, title: "Churchill loses the peace", era: "british", loc: "United Kingdom", blurb: "The election result is declared. The man who won the war is sent home. The public wants housing, not heroics. Fair, and brutal." },
  { m: 7, d: 6, y: 1535, title: "Thomas More executed", era: "tudors", loc: "Tower Hill", blurb: "He would not take the oath. Henry takes the head. A man for all seasons runs out of season." },
  { m: 7, d: 7, y: 1456, title: "Joan of Arc acquitted", era: "world", loc: "Rouen", blurb: "Twenty-five years late, a retrial. The fire is not undone. The paperwork is." },
  { m: 7, d: 8, y: 1497, title: "Vasco da Gama sails for India", era: "world", loc: "Lisbon", blurb: "Four ships, an unknown ocean, a route that will beggar Venice. Portugal punches above its weight, as usual." },
  { m: 7, d: 9, y: 1944, title: "Caen, at last", era: "ww2", loc: "Normandy", blurb: "A month after D-Day, the city falls. Montgomery’s timetable is a subject we will not get into in polite company." },
  { m: 7, d: 10, y: 1940, title: "Battle of Britain begins", era: "ww2", loc: "Southern England", blurb: "The Luftwaffe comes for the airfields. Dowding’s system, the radar, the Few. The island’s summer of 1940 starts in earnest.", video: "qbuXRiEbGFo" },
  { m: 7, d: 11, y: 1979, title: "Skylab comes home", era: "world", loc: "Western Australia", blurb: "America’s first space station re-enters, mostly over the Indian Ocean. Western Australia gets the souvenir fragments and a fine, later waived." },
  { m: 7, d: 12, y: 1543, title: "Henry marries Catherine Parr", era: "tudors", loc: "Hampton Court", blurb: "Wife number six, the one who survives. She can argue theology and keep her head. A rare skill set at this court." },
  { m: 7, d: 13, y: 1837, title: "Queen Victoria’s first train", era: "british", loc: "Slough to Paddington", blurb: "Royalty discovers the railway. The nineteenth century, previously a horse, puts on steam." },
  { m: 7, d: 14, y: 1789, title: "The Bastille", era: "world", loc: "Paris", blurb: "A prison, seven inmates, a symbol demolished. France starts a revolution and, shortly, a metric system." },
  { m: 7, d: 15, y: 1099, title: "Jerusalem taken", era: "world", loc: "Jerusalem", blurb: "The First Crusade succeeds, and then disgraces itself. The chronicles are not for the faint-hearted." },
  { m: 7, d: 16, y: 1945, title: "Trinity", era: "ww2", loc: "New Mexico", blurb: "The first atomic bomb. Oppenheimer thinks of Vishnu. The desert thinks of nothing. Hiroshima is three weeks away." },
  { m: 7, d: 17, y: 1918, title: "The Romanovs murdered", era: "world", loc: "Yekaterinburg", blurb: "A cellar in the Urals. A dynasty ends in small-arms fire. The bodies will take a century to settle." },
  { m: 7, d: 18, y: 64, title: "Rome burns", era: "romans", loc: "Rome", blurb: "Nero is out of town, whatever the fiddle story says. Christians will be blamed. A new palace will be planned on the ashes." },
  { m: 7, d: 19, y: 1545, title: "The Mary Rose sinks", era: "tudors", loc: "The Solent", blurb: "Henry VIII watches his favourite ship roll over in the Solent. Too many guns, too little freeboard, too much showing off." },
  { m: 7, d: 20, y: 1969, title: "Moon landing", era: "world", loc: "Sea of Tranquillity", blurb: "Armstrong, Aldrin, a flag that doesn’t wave. For one evening the species looks up instead of sideways." },
  { m: 7, d: 21, y: 1403, title: "Battle of Shrewsbury", era: "british", loc: "Shropshire", blurb: "Hotspur is killed. Prince Hal is wounded in the face and will later become Henry V, so the scar is a prequel." },
  { m: 7, d: 22, y: 1298, title: "Falkirk", era: "british", loc: "Stirlingshire", blurb: "Edward I breaks Wallace’s schiltrons with longbows. Braveheart the film will have notes. History has the body count." },
  { m: 7, d: 23, y: 1944, title: "The Majdanek camp revealed", era: "ww2", loc: "Lublin", blurb: "The Red Army overruns a death camp still standing. The West is about to lose the luxury of not knowing." },
  { m: 7, d: 24, y: 1567, title: "Mary Queen of Scots abdicates", era: "tudors", loc: "Lochleven", blurb: "Forced, in a castle on a lake. Her infant son becomes James VI. She still has a long, doomed road to Fotheringhay." },
  { m: 7, d: 25, y: 1909, title: "Blériot crosses the Channel", era: "world", loc: "Dover", blurb: "Thirty-seven minutes in a string bag. Britain is no longer an island in the way it thought. The RAF is nine years from being invented." },
  { m: 7, d: 26, y: 1945, title: "Churchill out, Attlee in", era: "british", loc: "Potsdam", blurb: "The Potsdam Conference changes prime ministers mid-sentence. Stalin is baffled. Labour builds the NHS." },
  { m: 7, d: 27, y: 1953, title: "Korean War armistice", era: "world", loc: "Panmunjom", blurb: "Fighting stops. The war does not officially end. The peninsula remains a frozen sentence." },
  { m: 7, d: 28, y: 1914, title: "Austria-Hungary declares war on Serbia", era: "ww2", loc: "Vienna", blurb: "The July crisis finds its war. The alliances do the rest, like a badly designed machine that only knows how to start." },
  { m: 7, d: 29, y: 1588, title: "The Armada, Gravelines", era: "tudors", loc: "The Channel", blurb: "English fireships, Dutch coasts, a west wind. Philip’s great fleet begins its long, lethal way home around Scotland." },
  { m: 7, d: 30, y: 1945, title: "USS Indianapolis sunk", era: "ww2", loc: "Pacific", blurb: "She has just delivered the bomb’s innards. The sharks do not care about the mission. It is one of the war’s crueller footnotes." },
  { m: 7, d: 31, y: 1703, title: "Daniel Defoe in the pillory", era: "british", loc: "London", blurb: "The crowd throw flowers, not rotten fruit. Satire, occasionally, is understood. Robinson Crusoe is still sixteen years off." },

  { m: 8, d: 1, y: 1834, title: "Slavery abolished in the British Empire", era: "british", loc: "Westminster", blurb: "The act takes effect. Compensation goes to the owners. The enslaved get their freedom, and a very long wait for the rest." },
  { m: 8, d: 2, y: 216, title: "Cannae", era: "romans", loc: "Apulia", blurb: "Hannibal’s masterpiece. A Roman army is enveloped and erased. Rome does not surrender. That, more than the tactics, is the point." },
  { m: 8, d: 3, y: 1492, title: "Columbus sails", era: "world", loc: "Palos", blurb: "Three ships, a wrong continent, and a hemisphere that will not be the same. The Taino have not been introduced." },
  { m: 8, d: 4, y: 1914, title: "Britain enters the Great War", era: "ww2", loc: "Westminster", blurb: "Belgium is the casus belli. Grey talks of the lamps going out. They will be out for four years." },
  { m: 8, d: 5, y: 1583, title: "Gilbert claims Newfoundland", era: "british", loc: "St John’s", blurb: "England’s first overseas colony, on paper. Gilbert will drown on the way home, quoting Thomas More. The empire starts as a drowning." },
  { m: 8, d: 6, y: 1945, title: "Hiroshima", era: "ww2", loc: "Japan", blurb: "8:15 a.m. A new kind of war in a single flash. The age that follows is lived under that cloud." },
  { m: 8, d: 7, y: 1420, title: "The dome of Florence consecrated, works ongoing", era: "world", loc: "Florence", blurb: "Brunelleschi’s impossible dome is rising. The Renaissance, in brick and nerve, has a skyline." },
  { m: 8, d: 8, y: 1588, title: "Elizabeth at Tilbury", era: "tudors", loc: "Essex", blurb: "‘I have the heart and stomach of a king.’ The Armada is already beaten at sea. The speech, as ever, wins the memory." },
  { m: 8, d: 9, y: 1945, title: "Nagasaki", era: "ww2", loc: "Japan", blurb: "The second bomb. The third is not required. Japan’s war has days." },
  { m: 8, d: 10, y: 1792, title: "The Tuileries stormed", era: "world", loc: "Paris", blurb: "The French monarchy is effectively over. The Swiss Guards die on the stairs. The Terror is in the post." },
  { m: 8, d: 11, y: 1492, title: "Rodrigo Borgia becomes pope", era: "world", loc: "Rome", blurb: "Alexander VI. The Renaissance papacy at its most family-minded. Machiavelli takes notes." },
  { m: 8, d: 12, y: 1676, title: "King Philip’s War, Metacom killed", era: "world", loc: "Rhode Island", blurb: "The bloodiest war in colonial New England ends with a death in a swamp. The name on the peace is not Native." },
  { m: 8, d: 13, y: 1961, title: "The Berlin Wall goes up", era: "world", loc: "Berlin", blurb: "Wire overnight, then concrete. A city is cut in half because people kept leaving. They will keep leaving anyway, later, through it." },
  { m: 8, d: 14, y: 1941, title: "The Atlantic Charter", era: "ww2", loc: "Newfoundland", blurb: "Churchill and Roosevelt on a warship, sketching a postwar world they have not yet won." },
  { m: 8, d: 15, y: 1945, title: "VJ Day", era: "ww2", loc: "World", blurb: "Japan surrenders. The most destructive war in history stops. The Cold War does not wait to be invented." },
  { m: 8, d: 16, y: 1819, title: "Peterloo", era: "british", loc: "Manchester", blurb: "A crowd wanting the vote is charged by cavalry. Fifteen dead. Reform, when it comes, will remember the names." },
  { m: 8, d: 17, y: 1424, title: "Battle of Verneuil", era: "british", loc: "Normandy", blurb: "A second Agincourt, less famous, just as ugly. English archery still has a few years left on the clock." },
  { m: 8, d: 18, y: 1227, title: "Genghis Khan dies", era: "world", loc: "Mongolia", blurb: "The empire does not. His sons have a map that already makes Rome look shy." },
  { m: 8, d: 19, y: 43, title: "Octavian, consul", era: "romans", loc: "Rome", blurb: "The future Augustus is forced into the consulship at nineteen. The Republic is already a costume." },
  { m: 8, d: 20, y: 1940, title: "Never in the field of human conflict", era: "ww2", loc: "Commons", blurb: "Churchill names The Few. The Battle of Britain is still being fought. The sentence is already immortal.", video: "KtxDaEX3-Sc" },
  { m: 8, d: 21, y: 1911, title: "The Mona Lisa stolen", era: "world", loc: "Louvre", blurb: "An Italian handyman walks out with her under his coat. She becomes more famous by vanishing. Paris is inconsolable, then obsessed." },
  { m: 8, d: 22, y: 1485, title: "Bosworth Field", era: "tudors", loc: "Leicestershire", blurb: "Richard III is cut down. Henry Tudor picks up a crown from a hawthorn bush. The Middle Ages end, give or take, in a Leicestershire field." },
  { m: 8, d: 22, y: 1642, title: "The King raises his standard", era: "civil-war", loc: "Nottingham", blurb: "Charles I declares war on his own parliament. The standard blows down in the night. Nobody takes the hint." },
  { m: 8, d: 23, y: 30, title: "Rome takes Egypt, more or less", era: "romans", loc: "Alexandria", blurb: "Octavian enters Alexandria around this season; Cleopatra’s Egypt is already a Roman story. The grain ships will now feed the Palatine." },
  { m: 8, d: 24, y: 79, title: "Vesuvius erupts", era: "romans", loc: "Bay of Naples", blurb: "Pompeii and Herculaneum vanish in a day. Pliny the Elder sails towards it, because of course he does, and does not sail back." },
  { m: 8, d: 25, y: 1944, title: "Paris liberated", era: "ww2", loc: "Paris", blurb: "Leclerc’s 2nd Armoured and the Resistance. De Gaulle walks down the Champs-Élysées as if he had never left." },
  { m: 8, d: 26, y: 1346, title: "Crécy", era: "british", loc: "Picardy", blurb: "English longbows, wet French cavalry, a blind king of Bohemia riding into the dark. The Hundred Years’ War finds its method." },
  { m: 8, d: 27, y: 1883, title: "Krakatoa", era: "world", loc: "Sunda Strait", blurb: "The sound is heard two thousand miles away. Sunsets turn red for years. The planet, briefly, shares a headache." },
  { m: 8, d: 28, y: 1963, title: "I have a dream", era: "world", loc: "Washington", blurb: "King on the steps of the Lincoln Memorial. A century after Gettysburg, the unfinished work is named in public." },
  { m: 8, d: 29, y: 1533, title: "Atahualpa executed", era: "world", loc: "Cajamarca", blurb: "Pizarro kills the Inca. A ransom in gold was not enough. Empires, when they can, prefer both." },
  { m: 8, d: 30, y: 30, title: "Cleopatra dies, traditionally", era: "romans", loc: "Alexandria", blurb: "Asp or poison, the brand is the asp. Antony is already dead. Egypt is a Roman province with better lighting." },
  { m: 8, d: 31, y: 1997, title: "Diana dies in Paris", era: "british", loc: "Paris", blurb: "A tunnel, a paparazzi chase, a week the country will not quite get over. The monarchy has to learn a new language overnight." },

  { m: 9, d: 1, y: 1939, title: "Poland invaded", era: "ww2", loc: "Poland", blurb: "Dawn, Stukas, the war that will not stay European. Britain and France have a treaty, and two days to honour it." },
  { m: 9, d: 2, y: 1666, title: "The Great Fire of London begins", era: "british", loc: "Pudding Lane", blurb: "A bakery, an east wind, a wooden city. Pepys buries his cheese. Wren will get the rebuild." },
  { m: 9, d: 3, y: 1939, title: "Britain declares war", era: "ww2", loc: "Westminster", blurb: "Chamberlain on the wireless, then the first air-raid siren. It is a false alarm. The war is not." },
  { m: 9, d: 4, y: 1870, title: "The Third Republic", era: "world", loc: "Paris", blurb: "Napoleon III has been captured at Sedan. France deposes him and improvises a republic. Prussia is still at the door." },
  { m: 9, d: 5, y: 1972, title: "Munich massacre", era: "world", loc: "Munich", blurb: "Olympic peace, broken in a night. Eleven Israeli athletes. The games, controversially, go on." },
  { m: 9, d: 6, y: 1522, title: "The Victoria comes home", era: "world", loc: "Sanlúcar", blurb: "One ship of Magellan’s five completes the first circumnavigation. The captain is not on it. Eighteen men are." },
  { m: 9, d: 7, y: 1533, title: "Elizabeth born", era: "tudors", loc: "Greenwich", blurb: "Anne Boleyn’s daughter. Not the boy Henry wanted. She will do, in the end, rather better than a boy." },
  { m: 9, d: 8, y: 1944, title: "The first V-2 on London", era: "ww2", loc: "Chiswick", blurb: "A rocket without warning. Hitler’s vengeance weapon arrives. There is no defence, only endurance." },
  { m: 9, d: 9, y: 1087, title: "William the Conqueror dies", era: "british", loc: "Rouen", blurb: "Injured on campaign, buried too small for his coffin. The man who won England in a day takes an undignified exit." },
  { m: 9, d: 10, y: 1897, title: "The first drunk-driving arrest", era: "british", loc: "London", blurb: "George Smith is arrested for driving a cab while drunk. The internal combustion engine has found its first regular customer: the magistrate." },
  { m: 9, d: 11, y: 2001, title: "September 11", era: "world", loc: "New York", blurb: "A clear morning. The century, which had been arguing about the end of history, is informed otherwise." },
  { m: 9, d: 12, y: 1683, title: "Vienna relieved", era: "world", loc: "Vienna", blurb: "Sobieski’s winged hussars crash into the Ottoman siege. Europe’s south-eastern door stays, for now, closed." },
  { m: 9, d: 13, y: 1759, title: "The Plains of Abraham", era: "british", loc: "Quebec", blurb: "Wolfe and Montcalm both die. Britain gets Canada. A short battle, a long consequence." },
  { m: 9, d: 14, y: 1752, title: "Britain skips eleven days", era: "british", loc: "United Kingdom", blurb: "The Gregorian calendar, 170 years late. Wednesday the 2nd is followed by Thursday the 14th. The mob, legend says, wants its fortnight back." },
  { m: 9, d: 15, y: 1940, title: "Battle of Britain Day", era: "ww2", loc: "Southern England", blurb: "The Luftwaffe’s maximum effort. Fighter Command does not break. Invasion, quietly, is postponed forever.", video: "qbuXRiEbGFo" },
  { m: 9, d: 16, y: 1620, title: "The Mayflower sails", era: "british", loc: "Plymouth", blurb: "A hundred souls and a compact still in draft. America, in one of its origin stories, leaves Devon." },
  { m: 9, d: 17, y: 1787, title: "The US Constitution signed", era: "world", loc: "Philadelphia", blurb: "A room of men, a compromise with slavery built in, a document that will be argued over longer than any of them live." },
  { m: 9, d: 18, y: 1810, title: "Chile’s first junta", era: "world", loc: "Santiago", blurb: "Spanish America starts unbuttoning the empire. The ripples will run the length of the Andes." },
  { m: 9, d: 19, y: 1356, title: "Poitiers", era: "british", loc: "France", blurb: "The Black Prince captures King John of France. England, briefly, has a French king in the bag and still cannot win the war." },
  { m: 9, d: 20, y: 1519, title: "Magellan leaves Seville", era: "world", loc: "Seville", blurb: "The voyage that will go round the world begins as a search for spices. Most of the crew will not complete the order." },
  { m: 9, d: 21, y: 1745, title: "Prestonpans", era: "british", loc: "East Lothian", blurb: "Bonnie Prince Charlie’s Highlanders smash Cope’s army in minutes. London, briefly, takes the Jacobites seriously." },
  { m: 9, d: 22, y: 1776, title: "Nathan Hale hanged", era: "world", loc: "New York", blurb: "‘I only regret that I have but one life.’ A twenty-one-year-old spy gives the Revolution a line it will keep." },
  { m: 9, d: 23, y: -480, title: "Salamis", era: "world", loc: "Saronic Gulf", blurb: "Around this stretch of autumn the Greeks trap Xerxes’ fleet at Salamis. Democracy, such as it is, gets to keep a coastline." },
  { m: 9, d: 24, y: 1941, title: "The Japanese war plan hardens", era: "ww2", loc: "Tokyo", blurb: "Imperial conferences through these weeks lock in a southern war. Pearl Harbor is no longer a theory." },
  { m: 9, d: 25, y: 1066, title: "Stamford Bridge", era: "british", loc: "Yorkshire", blurb: "Harold Godwinson smashes Harald Hardrada. Then he turns south, because 1066 does not do rest days. Hastings is three weeks away." },
  { m: 9, d: 26, y: 1580, title: "Drake completes the circumnavigation", era: "tudors", loc: "Plymouth", blurb: "The Golden Hind comes home stuffed with Spanish silver. Elizabeth knights him. Spain files a complaint." },
  { m: 9, d: 27, y: 1825, title: "Stockton and Darlington", era: "british", loc: "County Durham", blurb: "The first public steam railway. Locomotion No. 1. The world, shortly, will run on rails and coal and timetables." },
  { m: 9, d: 28, y: 1066, title: "William lands at Pevensey", era: "british", loc: "Pevensey Bay", blurb: "A Norman duke on a Sussex beach. Harold is still in the north, celebrating. The Martello towers are 740 years too late to help." },
  { m: 9, d: 29, y: 1829, title: "The Met is founded", era: "british", loc: "London", blurb: "Peel’s police walk the streets. The nickname ‘bobbies’ is the compliment that stuck." },
  { m: 9, d: 30, y: 1938, title: "Munich", era: "ww2", loc: "Munich", blurb: "Peace for our time. Chamberlain’s piece of paper. Czechoslovakia is not in the room. March 1939 will be the invoice." },

  { m: 10, d: 1, y: 1949, title: "The People’s Republic of China", era: "world", loc: "Beijing", blurb: "Mao on the gate of Heavenly Peace. A quarter of humanity has a new letterhead." },
  { m: 10, d: 2, y: 1187, title: "Saladin takes Jerusalem", era: "world", loc: "Jerusalem", blurb: "Eighty-eight years after the crusaders’ sack, the city changes hands more mercifully. Richard the Lionheart will come to argue." },
  { m: 10, d: 3, y: 1990, title: "Germany reunified", era: "world", loc: "Berlin", blurb: "Forty-five years after VE Day, one Germany again. The Wall’s ghost is a tourist attraction." },
  { m: 10, d: 4, y: 1957, title: "Sputnik", era: "world", loc: "Kazakhstan", blurb: "A beep from orbit. The Space Age starts as a Soviet party trick. America reaches for its textbooks." },
  { m: 10, d: 5, y: 1930, title: "The R101 crash", era: "british", loc: "Beauvais", blurb: "Britain’s imperial airship hits a French hillside. The age of the great British dirigible ends in the rain." },
  { m: 10, d: 6, y: 1973, title: "Yom Kippur War begins", era: "world", loc: "Sinai and Golan", blurb: "A surprise attack on the holiest day. The map of the Middle East, and the price of oil, will both move." },
  { m: 10, d: 7, y: 1571, title: "Lepanto", era: "world", loc: "Gulf of Patras", blurb: "Don John of Austria breaks the Ottoman fleet. Cervantes loses the use of a hand and gains a book." },
  { m: 10, d: 8, y: 1871, title: "The Great Chicago Fire", era: "world", loc: "Chicago", blurb: "The cow is a scapegoat. The wind is not. A wooden city learns about brick." },
  { m: 10, d: 9, y: 1967, title: "Che Guevara killed", era: "world", loc: "Bolivia", blurb: "A schoolhouse in the jungle. The poster outlives the guerrilla by decades." },
  { m: 10, d: 10, y: 1903, title: "Mrs Pankhurst’s WSPU", era: "british", loc: "Manchester", blurb: "Suffrage stops asking nicely. Windows, soon, will become a political medium." },
  { m: 10, d: 11, y: 1521, title: "Henry VIII, Defender of the Faith", era: "tudors", loc: "Rome", blurb: "The Pope gives Henry a title for attacking Luther. Henry will keep the title after attacking the Pope. Efficient." },
  { m: 10, d: 12, y: 1492, title: "Columbus makes landfall", era: "world", loc: "Bahamas", blurb: "He thinks it is Asia. It is not. The meeting of worlds is already irreversible." },
  { m: 10, d: 13, y: 54, title: "Claudius poisoned", era: "romans", loc: "Rome", blurb: "Mushrooms, Agrippina, and a teenage Nero waiting in the wings. The Julio-Claudians do not do quiet successions." },
  { m: 10, d: 14, y: 1066, title: "Hastings", era: "british", loc: "East Sussex", blurb: "Harold falls. William, still a duke at breakfast, is a conqueror by dusk. England is rewritten in French and feudalism." },
  { m: 10, d: 15, y: 1815, title: "Napoleon reaches St Helena", era: "world", loc: "St Helena", blurb: "The Atlantic’s most remote guest house. The emperor has time, and memoirs, and no army." },
  { m: 10, d: 16, y: 1793, title: "Marie Antoinette executed", era: "world", loc: "Paris", blurb: "The Austrian girl who became a French hate-figure. The crowd gets its spectacle. It does not get cheap bread." },
  { m: 10, d: 17, y: 1814, title: "The London Beer Flood", era: "british", loc: "St Giles", blurb: "A vat bursts in a brewery. Eight people drown in porter. Only in this country would disaster come on tap." },
  { m: 10, d: 18, y: 1016, title: "Assandun", era: "british", loc: "Essex", blurb: "Cnut beats Edmund Ironside. England is about to have a Danish king who will prove, inconveniently, rather good at it." },
  { m: 10, d: 19, y: 1781, title: "Yorktown", era: "world", loc: "Virginia", blurb: "Cornwallis surrenders. The band is said to play ‘The World Turned Upside Down.’ The American war, for Britain, is lost." },
  { m: 10, d: 20, y: 1805, title: "Ulm campaign, Mack surrenders", era: "world", loc: "Bavaria", blurb: "Napoleon bags an Austrian army without a proper battle. Trafalgar is tomorrow; this is the other shoe." },
  { m: 10, d: 21, y: 1805, title: "Trafalgar", era: "british", loc: "Off Cape Trafalgar", blurb: "Nelson dies at the moment of victory. France will not invade. Britannia, for a century, really does rule the waves." },
  { m: 10, d: 22, y: 1962, title: "Cuban Missile Crisis, Kennedy speaks", era: "world", loc: "Washington", blurb: "The world comes as close as it ever has. Thirteen days. A blockade that is called a quarantine, because words matter." },
  { m: 10, d: 23, y: 42, title: "Philippi, first fight", era: "romans", loc: "Macedonia", blurb: "Brutus and Cassius meet Antony and Octavian. The Republic’s last army is running out of republic." },
  { m: 10, d: 24, y: 1648, title: "Westphalia signed", era: "world", loc: "Münster and Osnabrück", blurb: "The Thirty Years’ War ends. Sovereignty is invented as a polite word for exhaustion." },
  { m: 10, d: 25, y: 1415, title: "Agincourt", era: "british", loc: "Picardy", blurb: "St Crispin’s Day. Mud, arrows, and a speech Shakespeare will improve. Henry V wins the battle and, eventually, a very difficult peace." },
  { m: 10, d: 25, y: 1854, title: "The Charge of the Light Brigade", era: "british", loc: "Crimea", blurb: "Someone blundered. Six hundred ride into the guns. Tennyson does the PR; the survivors do the rest of the war." },
  { m: 10, d: 26, y: 1863, title: "The Football Association founded", era: "british", loc: "London", blurb: "A set of rules in a tavern. The global religion of the working week is accidentally organised." },
  { m: 10, d: 27, y: 312, title: "The Milvian Bridge", era: "romans", loc: "Rome", blurb: "Constantine wins, and credits a Christian vision. The empire’s religion is about to change more thoroughly than its borders." },
  { m: 10, d: 28, y: 1918, title: "The German navy mutinies", era: "ww2", loc: "Kiel", blurb: "Sailors refuse a suicide sortie. The Kaiser’s war starts ending from the docks up." },
  { m: 10, d: 29, y: 1929, title: "Black Tuesday", era: "world", loc: "New York", blurb: "The crash. The jazz age hits the pavement. The 1930s will not be a party." },
  { m: 10, d: 30, y: 1938, title: "The War of the Worlds broadcast", era: "world", loc: "United States", blurb: "Orson Welles panics a portion of America with Martians in New Jersey. Radio, it turns out, is a weapon." },
  { m: 10, d: 31, y: 1517, title: "The Ninety-Five Theses", era: "world", loc: "Wittenberg", blurb: "Luther and a church door, or at least a very effective postal service. The Reformation begins as a complaint about indulgences and ends as a continent split." },

  { m: 11, d: 1, y: 1755, title: "Lisbon earthquake", era: "world", loc: "Lisbon", blurb: "All Saints’ Day, a city of churches, then fire and a wave. Voltaire writes a poem; Europe has a theodicy crisis." },
  { m: 11, d: 2, y: 1917, title: "The Balfour Declaration", era: "british", loc: "London", blurb: "A letter, a homeland, a century of consequences. The Foreign Office has written longer notes with smaller ripples." },
  { m: 11, d: 3, y: 64, title: "The Great Fire still burning", era: "romans", loc: "Rome", blurb: "Nero’s Rome is days into the blaze. A new city will be planned in brick. The fiddle, we must keep saying, is a later joke." },
  { m: 11, d: 4, y: 1922, title: "Tutankhamun’s tomb found", era: "world", loc: "Valley of the Kings", blurb: "Carter looks in. ‘Wonderful things.’ A boy-king becomes the most famous Egyptian who ever lived, mostly by staying put." },
  { m: 11, d: 5, y: 1605, title: "Gunpowder Plot", era: "british", loc: "Westminster", blurb: "Fawkes in the cellar, a leaky conspiracy, a king who keeps his parliament. Remember, remember — we certainly do." },
  { m: 11, d: 6, y: 1860, title: "Lincoln elected", era: "civil-war", loc: "United States", blurb: "A rail-splitter in a house divided. South Carolina starts packing for secession before the furniture is arranged." },
  { m: 11, d: 7, y: 1917, title: "The Bolsheviks take Petrograd", era: "world", loc: "Petrograd", blurb: "October in November, because of the calendar. The Winter Palace, a blank shot, a new kind of state." },
  { m: 11, d: 8, y: 1923, title: "The Beer Hall Putsch", era: "ww2", loc: "Munich", blurb: "Hitler’s rehearsal coup fails. Prison gives him a book. Germany, later, will give him rather more." },
  { m: 11, d: 9, y: 1989, title: "The Berlin Wall opens", era: "world", loc: "Berlin", blurb: "A bungled press conference, a night of hammers. The Cold War ends in a traffic jam of Trabants." },
  { m: 11, d: 10, y: 1871, title: "Stanley finds Livingstone", era: "british", loc: "Ujiji", blurb: "‘Dr Livingstone, I presume?’ The understatement of the Victorian age, in a village by a lake." },
  { m: 11, d: 11, y: 1918, title: "Armistice", era: "ww2", loc: "Compiègne", blurb: "Eleven o’clock. The guns stop. The peace will be badly written; the silence, for a morning, is enough." },
  { m: 11, d: 12, y: 1944, title: "Tirpitz sunk", era: "ww2", loc: "Tromsø", blurb: "Lancasters and Tallboys. The last German battleship is turned over in a Norwegian fjord. The Home Fleet can breathe." },
  { m: 11, d: 13, y: 1002, title: "St Brice’s Day massacre", era: "british", loc: "England", blurb: "Æthelred orders the killing of Danes in England. Sweyn Forkbeard will take this personally. The unready king lives up to the nickname." },
  { m: 11, d: 14, y: 1940, title: "Coventry blitzed", era: "ww2", loc: "Coventry", blurb: "The cathedral burns. A new verb, to coventrate, is briefly coined. The city rebuilds a modern nave beside the ruin." },
  { m: 11, d: 15, y: 1864, title: "Sherman’s March begins", era: "civil-war", loc: "Atlanta", blurb: "Atlanta burns behind him. The Confederacy is to be made to feel the war. It does." },
  { m: 11, d: 16, y: 1532, title: "Pizarro meets Atahualpa", era: "world", loc: "Cajamarca", blurb: "A handful of Spaniards, an empire of millions. Tomorrow’s ambush is already implicit in the invitation." },
  { m: 11, d: 17, y: 1558, title: "Elizabeth’s Accession Day", era: "tudors", loc: "England", blurb: "Mary I dies. The Protestant settlement, the Armada, the golden age — all of it starts with a twenty-five-year-old in Hatfield." },
  { m: 11, d: 18, y: 1626, title: "St Peter’s consecrated", era: "world", loc: "Rome", blurb: "The new basilica, a century in the making, is dedicated. The indulgences that paid for it have already split Europe." },
  { m: 11, d: 19, y: 1863, title: "The Gettysburg Address", era: "civil-war", loc: "Pennsylvania", blurb: "Two minutes, 272 words. Lincoln’s ‘few appropriate remarks’ outlive the two-hour speech they followed." },
  { m: 11, d: 20, y: 1945, title: "Nuremberg trials open", era: "ww2", loc: "Nuremberg", blurb: "Crimes against humanity enter the courtroom. ‘Just following orders’ is about to have a bad century." },
  { m: 11, d: 21, y: 1620, title: "The Mayflower Compact", era: "world", loc: "Cape Cod", blurb: "A floating agreement, signed because they have landed in the wrong place. Self-government, American-style, begins as a paperwork fix." },
  { m: 11, d: 22, y: 1963, title: "Kennedy assassinated", era: "world", loc: "Dallas", blurb: "A motorcade, a book depository, a weekend the cameras will not leave. The 1960s lose their president and keep their speed." },
  { m: 11, d: 23, y: 1499, title: "Perkin Warbeck executed", era: "tudors", loc: "Tyburn", blurb: "The pretender who might have been a prince, and probably wasn’t. Henry VII does not do loose ends." },
  { m: 11, d: 24, y: 1859, title: "On the Origin of Species", era: "british", loc: "London", blurb: "Darwin publishes. Theology reaches for the smelling salts. Biology gets a mechanism." },
  { m: 11, d: 25, y: 1120, title: "The White Ship sinks", era: "british", loc: "Barfleur", blurb: "Henry I’s heir drowns drunk off Normandy. The Anarchy is now a succession dispute waiting to happen." },
  { m: 11, d: 26, y: 1922, title: "Tutankhamun’s tomb opened", era: "world", loc: "Luxor", blurb: "Carter and Carnarvon step in. The curse is journalism. The gold is not." },
  { m: 11, d: 27, y: 1095, title: "Urban II calls the First Crusade", era: "world", loc: "Clermont", blurb: "‘Deus vult.’ A sermon, a movement, two centuries of war for a city none of the peasants will see." },
  { m: 11, d: 28, y: 1919, title: "Lady Astor elected", era: "british", loc: "Plymouth", blurb: "The first woman to take her seat in the Commons. The boys’ club has a new member, and is not thrilled." },
  { m: 11, d: 29, y: 1947, title: "The UN votes on Palestine", era: "world", loc: "New York", blurb: "Partition is passed. The map that follows is still being argued, in the same tense, now." },
  { m: 11, d: 30, y: 1874, title: "Churchill born", era: "british", loc: "Blenheim Palace", blurb: "A palace, a premature baby, a century that will need him in 1940 and tire of him in 1945." },

  { m: 12, d: 1, y: 1955, title: "Rosa Parks sits down", era: "world", loc: "Montgomery", blurb: "A bus, a refusal, a boycott. The civil rights movement finds a spark that was already a long fuse." },
  { m: 12, d: 2, y: 1805, title: "Austerlitz", era: "world", loc: "Moravia", blurb: "Napoleon’s masterpiece. Two emperors beaten in a morning. The Holy Roman Empire will shortly notice it is neither." },
  { m: 12, d: 3, y: 1810, title: "British take Mauritius", era: "british", loc: "Indian Ocean", blurb: "The French colonial island falls. The dodo is already gone. The harbour is the point." },
  { m: 12, d: 4, y: 1791, title: "The Observer first published", era: "british", loc: "London", blurb: "The world’s oldest Sunday paper. Scandal, already, is a business model." },
  { m: 12, d: 5, y: 1933, title: "Prohibition ends", era: "world", loc: "United States", blurb: "The 21st Amendment. America may drink again, legally. The gangsters will need a new product." },
  { m: 12, d: 6, y: 1917, title: "Halifax explosion", era: "world", loc: "Nova Scotia", blurb: "A munitions ship in harbour. The largest man-made bang before the atomic age. A city flattened before breakfast." },
  { m: 12, d: 7, y: 1941, title: "Pearl Harbor", era: "ww2", loc: "Hawaii", blurb: "A Sunday morning in the Pacific. America is in the war before lunch. Yamamoto has the victory, and the misgiving." },
  { m: 12, d: 8, y: 1941, title: "Britain and America at war with Japan", era: "ww2", loc: "Westminster", blurb: "Churchill sleeps ‘the sleep of the saved.’ The war is now genuinely world-sized." },
  { m: 12, d: 9, y: 1917, title: "Allenby takes Jerusalem", era: "ww2", loc: "Jerusalem", blurb: "He enters on foot. Eight hundred years after the crusaders, a British general has the city, and a photograph." },
  { m: 12, d: 10, y: 1688, title: "James II’s son is smuggled to France", era: "british", loc: "London", blurb: "The warming-pan legend, the Glorious Revolution in motion. A male heir, badly timed, finishes a king." },
  { m: 12, d: 11, y: 1936, title: "Edward VIII abdicates", era: "british", loc: "Windsor", blurb: "For love, and a microphone. The Empire is not consulted. George VI inherits a stammer and a coming war." },
  { m: 12, d: 12, y: 1939, title: "The Battle of the River Plate, brewing", era: "ww2", loc: "South Atlantic", blurb: "HMS Exeter and friends are hunting the Graf Spee. In days, Montevideo will have a front-row seat." },
  { m: 12, d: 13, y: 1577, title: "Drake leaves on his circumnavigation", era: "tudors", loc: "Plymouth", blurb: "Officially, a trading voyage. Unofficially, a licensed raid on the Spanish Pacific. Elizabeth understands deniability." },
  { m: 12, d: 14, y: 1911, title: "Amundsen at the South Pole", era: "world", loc: "Antarctica", blurb: "Dogs, skis, a Norwegian flag. Scott is still dragging a sledge. The race is already over." },
  { m: 12, d: 15, y: 1791, title: "The Bill of Rights ratified", era: "world", loc: "United States", blurb: "Ten amendments. A revolution writes itself a list of things government may not do. Lawyers rejoice, forever." },
  { m: 12, d: 16, y: 1773, title: "Boston Tea Party", era: "world", loc: "Boston", blurb: "A dressing-up box and a harbour. Britain loses the plot, and shortly the colonies. Tax remains a sensitive subject." },
  { m: 12, d: 17, y: 1903, title: "The Wright brothers fly", era: "world", loc: "Kitty Hawk", blurb: "Twelve seconds. The twentieth century leaves the ground and will, in forty years, have to fight over it." },
  { m: 12, d: 18, y: 1916, title: "Verdun ends", era: "ww2", loc: "Verdun", blurb: "Ten months, three-quarters of a million casualties, a city that held. France’s sacred wound." },
  { m: 12, d: 19, y: 1732, title: "Benjamin Franklin’s Poor Richard", era: "world", loc: "Philadelphia", blurb: "An almanac of maxims. America learns to like being lectured if the lecturer is funny." },
  { m: 12, d: 20, y: 69, title: "Vespasian’s year, still messy", era: "romans", loc: "Rome", blurb: "The Year of the Four Emperors is winding towards Flavian order. Rome has had enough of the audition process." },
  { m: 12, d: 21, y: 1620, title: "Mayflower, Plymouth Rock", era: "world", loc: "Massachusetts", blurb: "A landing, a winter, a myth that will be polished smoother than the rock." },
  { m: 12, d: 22, y: 1989, title: "Ceaușescu falls", era: "world", loc: "Bucharest", blurb: "Romania’s revolution, the last and the bloodiest of that year. A balcony speech that does not work. Christmas will not be kind." },
  { m: 12, d: 23, y: 1888, title: "Van Gogh and the ear", era: "world", loc: "Arles", blurb: "A breakdown, a bandage, a painting. The nineteenth century’s most expensive medical incident." },
  { m: 12, d: 24, y: 1914, title: "The Christmas truce", era: "ww2", loc: "Western Front", blurb: "Carols in no man’s land, a football, a day that generals will not allow twice. The war resumes on Boxing Day, because of course it does." },
  { m: 12, d: 25, y: 1066, title: "William crowned", era: "british", loc: "Westminster Abbey", blurb: "Christmas Day, a new king, the guards outside panic at the shouting and set fire to the neighbourhood. A very Norman nativity." },
  { m: 12, d: 26, y: 1943, title: "The Battle of North Cape", era: "ww2", loc: "Arctic", blurb: "Scharnhorst is sunk in the dark. The Arctic convoys keep going. Murmansk, somehow, still gets its ships." },
  { m: 12, d: 27, y: 1831, title: "Darwin sails on the Beagle", era: "british", loc: "Plymouth", blurb: "A gentleman naturalist, a five-year voyage, a finch. Theology should have stopped him at the dock." },
  { m: 12, d: 28, y: 1879, title: "The Tay Bridge disaster", era: "british", loc: "Dundee", blurb: "A storm, a train, a bridge that was a boast. Victorian engineering learns about wind, the hard way." },
  { m: 12, d: 29, y: 1170, title: "Becket murdered", era: "british", loc: "Canterbury", blurb: "Four knights, a cathedral, a king who said too much. ‘Will no one rid me of this turbulent priest?’ — and then, immediately, regret." },
  { m: 12, d: 30, y: 1460, title: "Wakefield", era: "british", loc: "Yorkshire", blurb: "Richard of York is killed. His head will wear a paper crown on Micklegate. The Wars of the Roses do irony without trying." },
  { m: 12, d: 31, y: 1923, title: "The chimes of Big Ben on the wireless", era: "british", loc: "London", blurb: "The BBC broadcasts the bells. A century of New Year’s Eves now has a soundtrack, and a countdown to arguments about the fireworks." },
];

const byKey = new Map();
for (const event of [...EVENTS, ...EXTRA, ...FILL]) {
  const key = `${event.m}-${event.d}`;
  if (!byKey.has(key)) byKey.set(key, []);
  const list = byKey.get(key);
  if (list.some((item) => item.y === event.y && item.title === event.title)) continue;
  list.push(event);
}

export function eventsFor(month, day) {
  const list = byKey.get(`${month}-${day}`) ?? [];
  return list.slice().sort((a, b) => a.y - b.y);
}

export function hasEvents(month, day) {
  return eventsFor(month, day).length > 0;
}

export function hasVideo(month, day) {
  return hasShort(month, day) || (byKey.get(`${month}-${day}`) ?? []).some((e) => e.video);
}

export function allDatesWithVideos() {
  const out = [];
  for (const [key, list] of byKey) {
    if (list.some((e) => e.video)) {
      const [m, d] = key.split("-").map(Number);
      out.push({ m, d });
    }
  }
  return out;
}

export function randomEvent() {
  return EVENTS[Math.floor(Math.random() * EVENTS.length)];
}

export function eraLabel(id) {
  return ERAS.find((e) => e.id === id)?.label ?? id;
}
