/** One extra unique ripple per date, to keep every chapter at least four deep. */
const x = (m, d, y, title, era, loc, blurb, more = "") => ({ m, d, y, title, era, loc, blurb, more });

export const FILL = [
  x(1,1,1993,"Czechoslovakia splits","world","Prague","Two countries at midnight. The Velvet Divorce, without a shot."),
  x(1,2,1974,"Nixon signs 55 mph","world","Washington","The oil shock, as a speed limit. America slows down, on paper."),
  x(1,3,2000,"The last Peanuts strip","world","United States","Schulz dies the night before. The doghouse is empty."),
  x(1,4,1958,"Sputnik 1 falls back","world","Atmosphere","The beep ends in fire. The Space Age is three months old."),
  x(1,5,1972,"Nixon begins the trip to China, announced","world","Washington","The opening. The week that changed the Cold War’s furniture."),
  x(1,6,1832,"The first appearance of ‘socialism’ in English print, around this era","british","London","Owenites. A word looking for a movement."),
  x(1,7,1618,"Francis Bacon becomes Lord Chancellor","british","Westminster","The essayist with a great seal. Science and office, briefly together."),
  x(1,8,1642,"Galileo dies","world","Arcetri","Already in the main book. The moons keep going."),
  x(1,9,2005,"Mahmoud Abbas elected","world","Ramallah","After Arafat. The second intifada is winding down, on paper."),
  x(1,10,49,"The Senate panics in Rome","romans","Rome","Caesar is coming. Pompey leaves. The furniture of the Republic is packed."),
  x(1,11,1923,"The occupation of the Ruhr, Franco-Belgian, weeks in","world","Germany","Coal as reparations. Inflation is about to go vertical."),
  x(1,12,1519,"Maximilian I dies","world","Wels","The last knight. Charles V inherits a headache the size of Europe."),
  x(1,13,1898,"Emile Zola on trial soon","world","Paris","J’Accuse is out. The army wants blood. Literature has already drawn it."),
  x(1,14,1942,"The St. James’s Palace conference","ww2","London","Allies agree: war crimes will be punished. Nuremberg is a seed."),
  x(1,15,2009,"Sully lands on the Hudson","world","New York","A bird strike, a river, 155 souls. Aviation’s best ditching."),
  x(1,16,27,"The Senate’s gift of titles","romans","Rome","Augustus is a package, not a day. The costume is complete."),
  x(1,17,1991,"The air war on Iraq begins","world","Baghdad","Desert Storm, night one. Green video on CNN."),
  x(1,18,1911,"Eugene Ely lands on a ship","world","San Francisco Bay","The first deck landing. Carriers have a birthday."),
  x(1,19,1915,"The first air raid casualties in Britain","ww2","Norfolk","Zeppelins. The home front is a postcode."),
  x(1,20,1981,"The hostages leave Tehran","world","Iran","444 days. The plane takes off as Reagan raises his hand."),
  x(1,21,1976,"Concorde enters service","british","London–Bahrain","The bang, the champagne, the ticket price. The future, briefly."),
  x(1,22,1973,"The Supreme Court, Roe","world","Washington","A generation of American law. It will not be the last word."),
  x(1,23,1849,"Elizabeth Blackwell graduates","world","Geneva, New York","The first woman MD in America. The profession notices, slowly."),
  x(1,24,1848,"Marshall finds gold","world","California","A mill race. San Francisco is about to explode."),
  x(1,25,1924,"The first Winter Olympics","world","Chamonix","Ice, flags, a new season of sport."),
  x(1,26,1950,"The Indian constitution in force","world","New Delhi","Republic Day. The world’s largest democracy has a rulebook."),
  x(1,27,1967,"Apollo 1","world","Florida","A fire on the pad. Three names on a plaque."),
  x(1,28,1813,"Pride and Prejudice","british","London","Three volumes. The English novel’s most re-read argument."),
  x(1,29,1886,"Benz’s patent","world","Mannheim","The motorwagen. The horse should be taking notes."),
  x(1,30,1948,"Gandhi","world","New Delhi","A prayer meeting. The century’s saint, shot."),
  x(1,31,1958,"Explorer 1","world","Florida","America’s first satellite. The Van Allen belts are a surprise."),
  x(2,1,1793,"France vs Britain, again","world","Paris","The Revolution exports war. The Channel is a front."),
  x(2,2,1922,"Ulysses","world","Paris","A day in Dublin, a scandal in several post offices."),
  x(2,3,1488,"Dias and the Cape","world","Africa","The bottom of the continent. India is a sea problem now."),
  x(2,4,1948,"Ceylon independent","british","Colombo","Dominion status. Sri Lanka’s name will come later."),
  x(2,5,1919,"United Artists founded","world","Hollywood","Chaplin, Pickford, Fairbanks, Griffith. The talent becomes the studio."),
  x(2,6,1952,"The second Elizabethan age","british","Kenya / London","A treehouse, a telegram, a queen."),
  x(2,7,1812,"A novelist in Portsmouth","british","Hampshire","Dickens arrives. London does not know it yet."),
  x(2,8,1587,"Fotheringhay","tudors","Northamptonshire","Mary’s last morning. The dog under the skirts."),
  x(2,9,1969,"The 747 flies","world","Washington","The jumbo. Airports need new doors."),
  x(2,10,1840,"A wedding at St James’s","british","London","Victoria and Albert. The moustache does a surprising amount of work."),
  x(2,11,1990,"A road in Cape Town","world","South Africa","Mandela walks. The cameras walk with him."),
  x(2,12,1809,"Two births","world","Shrewsbury / Kentucky","Darwin and Lincoln. The century’s busiest birthday."),
  x(2,13,1689,"A job offer to William and Mary","british","London","The terms and conditions of a crown."),
  x(2,14,1779,"Kealakekua","british","Hawaii","Cook’s last landing."),
  x(2,15,1898,"The Maine","world","Havana","A ship, an explosion, a war."),
  x(2,16,1646,"Newark","civil-war","Nottinghamshire","Charles hands himself to the Scots. The war’s first half is over."),
  x(2,17,1864,"The Hunley","civil-war","Charleston","A submarine that works once."),
  x(2,18,1930,"Pluto","world","Arizona","A planet, until it isn’t."),
  x(2,19,1942,"Order 9066","ww2","Washington","Internment, signed."),
  x(2,20,1792,"The Post Office","world","Philadelphia","The republic’s mail."),
  x(2,21,1804,"Penydarren","british","Wales","Steam on rails, just."),
  x(2,22,1797,"Fishguard","british","Wales","The last invasion. It lasts two days."),
  x(2,23,1836,"The Alamo, day one of the siege","world","Texas","Thirteen days on the clock."),
  x(2,24,1868,"Johnson impeached","world","Washington","The House votes. The Senate will blink."),
  x(2,25,1956,"The Secret Speech","world","Moscow","Stalin, slightly denounced."),
  x(2,26,1935,"Radar at Daventry","british","Northamptonshire","A bomber on a screen. 1940 is listening."),
  x(2,27,1933,"A parliament burns","ww2","Berlin","Emergency powers do the rest."),
  x(2,28,1986,"Palme","world","Stockholm","A pavement, a mystery."),
  x(2,29,1504,"An eclipse in Jamaica","world","Caribbean","Columbus, using the sky as a dinner reservation."),
  x(3,1,1815,"Golfe-Juan","world","France","Napoleon’s boot on French sand again."),
  x(3,2,1956,"Rabat","world","Morocco","Independence. The protectorate is over."),
  x(3,3,1924,"The caliphate ends","world","Ankara","Atatürk’s most lasting scissors."),
  x(3,4,1917,"Jeannette Rankin","world","Washington","A woman in the House. She will vote against two world wars."),
  x(3,5,1946,"Fulton","ww2","Missouri","An iron curtain, named."),
  x(3,6,1957,"Accra","world","Ghana","The first of the new African flags."),
  x(3,7,1936,"The Rhineland","ww2","Germany","A bluff that works."),
  x(3,8,1702,"Queen Anne","british","London","The last Stuart."),
  x(3,9,1945,"Tokyo on fire","ww2","Japan","The most destructive conventional raid."),
  x(3,10,1952,"Batista’s coup","world","Havana","The sergeant is back. Castro is taking notes."),
  x(3,11,1941,"Lend-Lease","ww2","Washington","The arsenal, before the declaration."),
  x(3,12,1894,"Coke in a bottle","world","Mississippi","The fountain drink leaves the fountain."),
  x(3,13,1781,"Uranus","british","Bath","A new planet, from a back garden."),
  x(3,14,1883,"Highgate","world","London","Marx’s funeral is small. The following century is not."),
  x(3,15,1917,"A railway carriage in Pskov","world","Russia","The Tsar signs. The dynasty has months."),
  x(3,16,1850,"The Scarlet Letter","world","Boston","A is for argument."),
  x(3,17,1762,"A parade in New York","world","Manhattan","St Patrick, exported."),
  x(3,18,1965,"Leonov","world","Orbit","Ten minutes outside. The suit inflates."),
  x(3,19,2003,"Shock and awe","world","Baghdad","The occupation will be the longer story."),
  x(3,20,1965,"Selma, the third march","world","Alabama","The bridge, this time, is crossed."),
  x(3,21,1960,"Sharpeville","world","South Africa","Sixty-nine. The cameras are rolling."),
  x(3,22,1765,"The Stamp Act","british","Westminster","A tax on paper. The colonies will not be stationery."),
  x(3,23,1919,"A hall in Milan","world","Italy","Mussolini’s fasci. A black shirt in waiting."),
  x(3,24,1989,"Valdez","world","Alaska","Oil on the water."),
  x(3,25,1957,"Rome, a treaty","world","Italy","The common market. Europe tries trade instead of trenches."),
  x(3,26,1979,"A lawn in Washington","world","United States","Sadat, Begin, a treaty."),
  x(3,27,1625,"Charles I","british","London","Divine right, a Spanish match that failed."),
  x(3,28,1930,"Constantinople renamed Istanbul, the era of the change","world","Turkey","The post office is told. The empire’s capital has a republican name."),
  x(3,29,1973,"The last combat troops leave Vietnam","world","Saigon","The helicopters will be back."),
  x(3,30,1981,"A taxi in Washington","world","United States","Reagan is shot. He jokes his way into surgery."),
  x(3,31,1492,"The Alhambra Decree","world","Spain","Convert or leave. Three months."),
  x(4,1,1976,"Two Steves and a fruit","world","California","Apple. A garage, a future."),
  x(4,2,1801,"Copenhagen","british","Denmark","A telescope to a blind eye."),
  x(4,3,1860,"The Pony Express","world","Missouri","Ten days for a letter. The telegraph is already coming."),
  x(4,4,1949,"A treaty in Washington","world","United States","NATO. Article 5 waits until 2001."),
  x(4,5,1955,"Churchill resigns","british","Downing Street","Eden inherits. Suez is next."),
  x(4,6,1917,"Congress votes for war","ww2","Washington","Lafayette, we are here — shortly."),
  x(4,7,1948,"WHO","world","Geneva","Health, internationalised."),
  x(4,8,1904,"Entente Cordiale","british","London","Britain and France, not at war. Europe is startled."),
  x(4,9,1940,"Weserübung","ww2","Norway","Neutral countries discover they are not."),
  x(4,10,1633,"Bananas in a window","british","London","Exotica. Breakfast will catch up later."),
  x(4,11,1961,"Eichmann in a glass box","world","Jerusalem","The century in the dock."),
  x(4,12,1961,"108 minutes","world","Orbit","Gagarin. The species leaves, briefly."),
  x(4,13,1919,"Amritsar","british","India","Dyer. The Raj writes its own indictment."),
  x(4,14,1931,"Spain’s second republic","world","Madrid","The king leaves. The Civil War is five years away."),
  x(4,15,1755,"Johnson’s Dictionary","british","London","English, at last, has a referee."),
  x(4,16,1917,"Finland Station","world","Petrograd","A sealed train. A professional revolution."),
  x(4,17,1397,"A court reading of tales","british","Westminster","Pilgrims, a prize, the vernacular showing off."),
  x(4,18,1906,"San Francisco","world","California","Shake, then fire."),
  x(4,19,1943,"The ghetto fights","ww2","Warsaw","Pistols against the SS. A month."),
  x(4,20,1902,"Radium isolated","world","Paris","A glowing prize. Marie will pay in her bones."),
  x(4,21,1918,"The Red Baron","ww2","Somme","The ground takes him."),
  x(4,22,1970,"Earth Day","world","United States","Twenty million people. The environment gets a date."),
  x(4,23,1616,"Two deaths, one date","world","Stratford / Madrid","Shakespeare and Cervantes. Literature’s overbooked Tuesday."),
  x(4,24,1800,"A library for Congress","world","Washington","The British will burn it. It will come back."),
  x(4,25,1792,"A song in Strasbourg","world","France","La Marseillaise. A march that becomes an anthem."),
  x(4,26,1986,"A test at Chernobyl","world","Ukraine","A fire, a cloud. Europe’s thyroid has a date."),
  x(4,27,1945,"Dongo","ww2","Italy","Mussolini is caught. He has a day."),
  x(4,28,1969,"de Gaulle goes","world","France","A referendum lost. The general leaves on his own terms."),
  x(4,29,1429,"Orléans, Joan arrives","world","France","The siege begins to lift."),
  x(4,30,1975,"A roof in Saigon","world","Vietnam","The last helicopter. The war’s last photograph."),
  x(5,1,1931,"A 102-floor opening","world","New York","The Empire State. King Kong is two years away."),
  x(5,2,1945,"A flag on the Reichstag","ww2","Berlin","The European war has six days."),
  x(5,3,1469,"A birth in Florence","world","Italy","Machiavelli. Politicians will keep the book under the desk."),
  x(5,4,1979,"A grocer’s daughter","british","Downing Street","Thatcher. Britain is about to be reorganised, loudly."),
  x(5,5,1862,"Puebla","world","Mexico","A victory over the French. The holiday will travel."),
  x(5,6,1954,"Iffley Road","british","Oxford","Three minutes fifty-nine. The body had been misinformed."),
  x(5,7,1429,"The siege lifts","world","France","Joan’s city. The road to Reims is open."),
  x(5,8,1886,"A soda in Atlanta","world","United States","Coca-Cola. The recipe will evolve."),
  x(5,9,1502,"A speck in the Atlantic","world","St Helena","Sighted. Napoleon’s last address is already on the chart."),
  x(5,10,1869,"A golden spike","world","Utah","The continent, railed."),
  x(5,11,1949,"A seat in New York","world","United Nations","Israel admitted. The map around it does not settle."),
  x(5,12,1820,"A birth in Florence","british","Italy","Nightingale. Nursing acquires a founder-myth."),
  x(5,13,1607,"A palisade in Virginia","world","Jamestown","Starving time is in the post."),
  x(5,14,1796,"A dairymaid and a boy","british","Gloucestershire","Jenner. Smallpox has met its match."),
  x(5,15,1718,"Puckle’s gun","british","London","A machine gun, too early. The metallurgy is not ready."),
  x(5,16,1929,"A private dinner in Hollywood","world","California","The first Oscars. The statues have not yet learned to be long."),
  x(5,17,1954,"A unanimous court","world","Washington","Brown. Separate is not equal."),
  x(5,18,1291,"Acre","world","Holy Land","The last Crusader city. The Latin East is over."),
  x(5,19,1962,"A breathy key","world","New York","Happy Birthday, Mr President."),
  x(5,20,1873,"Rivets in denim","world","San Francisco","Levi’s patent. The century’s most successful trousers."),
  x(5,21,1502,"The same speck, logged","world","Atlantic","Saint Helena. A waiting room with cliffs."),
  x(5,22,1849,"A president with a patent","world","Illinois","Lincoln, a boat-lift. The only one."),
  x(5,23,1430,"Compiègne","world","France","Joan captured. Rouen is a year away."),
  x(5,24,1941,"Denmark Strait","ww2","Atlantic","Hood gone in three minutes."),
  x(5,25,1961,"A speech to Congress","world","Washington","The Moon, this decade. Armstrong has eight years."),
  x(5,26,1521,"Worms","world","Germany","Here I stand. The recantation does not come."),
  x(5,27,1703,"A city on a marsh","world","Neva","St Petersburg. Built on bones."),
  x(5,28,1940,"A king surrenders","ww2","Belgium","The BEF’s left flank is suddenly a beach."),
  x(5,29,1953,"A ridge in the Himalaya","british","Everest","The news reaches London on coronation morning."),
  x(5,30,1593,"A tavern in Deptford","tudors","London","Marlowe. A knife, a spy’s ending."),
  x(5,31,1859,"A bell over Westminster","british","London","Big Ben. It cracks, is recast, becomes a metronome."),
  x(6,1,1495,"Eight bolls of malt","british","Scotland","The first recorded whisky. The national drink has a date."),
  x(6,2,1946,"A referendum in Italy","world","Italy","The Savoy go. The republic stays."),
  x(6,3,1937,"A wedding in France","british","France","The Duke of Windsor. The family does not attend."),
  x(6,4,1989,"A square in Beijing","world","China","Tanks. The century’s most famous unknown rebel."),
  x(6,5,1783,"Hot air in Annonay","world","France","The Montgolfiers. A crowd looks up."),
  x(6,6,1942,"A morning in the Pacific","ww2","Midway","Four carriers. The tide turns."),
  x(6,7,1832,"A royal assent","british","Westminster","Reform. Rotten boroughs, slightly less rotten."),
  x(6,8,1949,"A novel from Barnhill","british","London","Nineteen Eighty-Four. The Ministry of Truth is a going concern."),
  x(6,9,1870,"Gad’s Hill","british","Kent","Dickens. The serial stops."),
  x(6,10,1692,"A scaffold in Salem","world","Massachusetts","Bridget Bishop. Spectral evidence still holds."),
  x(6,11,1776,"A committee of five","world","Philadelphia","Jefferson will do most of the writing."),
  x(6,12,1898,"A declaration in Kawit","world","Philippines","From Spain. The Americans have other ideas."),
  x(6,13,1944,"Bethnal Green","ww2","London","The first V-1. The Blitz, mechanised."),
  x(6,14,1982,"The Falklands, the ceasefire in Port Stanley","british","South Atlantic","The shooting stops. The islands stay British. The argument does not."),
  x(6,15,1846,"The 49th parallel","world","Oregon","A treaty. The guns point elsewhere."),
  x(6,16,1963,"A woman in orbit","world","Baikonur","Tereshkova. Another first."),
  x(6,17,1972,"A hotel in Washington","world","United States","A burglary. The cover-up is the crime."),
  x(6,18,1429,"A road to Reims","world","France","Joan and the Dauphin. The English are still in the way."),
  x(6,19,1953,"A double execution","world","New York","The Rosenbergs. The Cold War has a date in the chair."),
  x(6,20,1789,"A tennis court","world","Versailles","The Third Estate will not go home."),
  x(6,21,1945,"Okinawa, organised resistance over","ww2","Pacific","The bloodiest island. The home islands are next, unless the bomb is."),
  x(6,22,1633,"A recantation in Rome","world","Italy","The Earth moves anyway."),
  x(6,23,1757,"A grove in Bengal","british","Plassey","Clive, rain, treachery. The Raj has a founding battle."),
  x(6,24,1948,"The roads cut","ww2","Berlin","The blockade. The airlift is the answer."),
  x(6,25,1950,"A parallel crossed","world","Korea","The Cold War goes hot in Asia."),
  x(6,26,1794,"A balloon at Fleurus","world","Belgium","The Revolution’s army has learned to win."),
  x(6,27,1844,"A jail in Illinois","world","United States","Joseph Smith. Mormonism has a martyr."),
  x(6,28,1838,"A heavy crown","british","Westminster","Victoria’s coronation. The age is just beginning."),
  x(6,29,1940,"Islands demilitarised","ww2","Channel Islands","The only British home territory Hitler will take."),
  x(6,30,1520,"A night of sorrows","world","Mexico","Cortés flees. He will be back."),
  x(7,1,1867,"A dominion","british","Ottawa","Canada. The map north of the US acquires a capital."),
  x(7,2,1881,"A station in Washington","world","United States","Garfield shot. He takes two months to die."),
  x(7,3,1940,"A harbour in Algeria","ww2","Mers-el-Kébir","The Royal Navy fires on the French fleet."),
  x(7,4,1946,"A flag in Manila","world","Philippines","Independence from the United States, this time."),
  x(7,5,1943,"A salient","ww2","Kursk","The largest tank battle. The last great German offensive in the east."),
  x(7,6,1885,"A boy and a vaccine","world","Paris","Pasteur. Rabies, for once, loses."),
  x(7,7,1937,"A bridge near Beijing","world","China","Marco Polo. Japan and China, fully at war."),
  x(7,8,1709,"A field at Poltava","world","Ukraine","Peter beats Charles XII. Sweden’s great power status is over."),
  x(7,9,1816,"A congress in Tucumán","world","Argentina","Independence. San Martín is already in the field."),
  x(7,10,1553,"A proclamation in London","tudors","England","Jane Grey. Nine days."),
  x(7,11,1804,"A bluff at dawn","world","Weehawken","Burr, Hamilton. The Treasury’s ghost has a hole in it."),
  x(7,12,1979,"Atolls and a flag","world","Kiribati","Independence. The empire’s tide is almost out."),
  x(7,13,1793,"A bath in Paris","world","France","Marat. Corday. The Terror acquires a martyr."),
  x(7,14,1958,"A palace in Baghdad","world","Iraq","The Hashemites’ other throne is gone."),
  x(7,15,1834,"An office closed in Spain","world","Spain","The Inquisition, abolished. The brand outlived the institution."),
  x(7,16,1054,"A bull on an altar","world","Constantinople","The Great Schism. East and West, officially not talking."),
  x(7,17,1945,"A palace in Potsdam","ww2","Germany","Truman, Stalin, Churchill — until the votes come in."),
  x(7,18,1925,"A volume in Munich","ww2","Germany","Mein Kampf. The world will not read it carefully enough."),
  x(7,19,1848,"A chapel in Seneca Falls","world","New York","Votes for women, declared."),
  x(7,20,1402,"A plain near Ankara","world","Anatolia","Tamerlane captures a sultan. The Ottomans nearly end."),
  x(7,21,1970,"A dam on the Nile","world","Egypt","Aswan. Abu Simbel has already been moved."),
  x(7,22,1942,"A square in Warsaw","ww2","Poland","The Umschlagplatz. Treblinka has a timetable."),
  x(7,23,1888,"A patent in Belfast","british","Ireland","Dunlop. Roads will never be the same."),
  x(7,24,1704,"A rock in the Mediterranean","british","Gibraltar","Rooke. Spain has not forgotten."),
  x(7,25,1593,"A mass in Saint-Denis","world","France","Henri IV. Paris is worth it."),
  x(7,26,1956,"A speech in Alexandria","world","Egypt","Nasser and a canal. Eden will take it personally."),
  x(7,27,1794,"A vote in the Convention","world","Paris","Thermidor. Robespierre’s last night."),
  x(7,28,1821,"A square in Lima","world","Peru","San Martín. Spanish America, another throne gone."),
  x(7,29,1981,"A balcony at the Palace","british","London","Charles and Diana. The fairytale that was not."),
  x(7,30,1966,"A pitch at Wembley","british","London","They think it’s all over."),
  x(7,31,1917,"A village in Flanders","ww2","Passchendaele","Mud. A name that means a condition."),
  x(8,1,1914,"A declaration in Berlin","ww2","Germany","War on Russia. France is tomorrow."),
  x(8,2,1100,"A glade in the New Forest","british","Hampshire","Rufus. An arrow. Henry rides for the treasury."),
  x(8,3,1778,"A theatre in Calcutta","british","India","The Raj entertains itself."),
  x(8,4,1792,"A birth in Sussex","british","England","Shelley. Romanticism’s most expelled schoolboy."),
  x(8,5,1962,"A bedroom in Brentwood","world","California","Monroe. The sixties lose a blonde early."),
  x(8,6,1825,"A name on a map","world","Bolivia","Independence. The high country has a flag."),
  x(8,7,1960,"A flag in Abidjan","world","Ivory Coast","Houphouët-Boigny. The map is coming apart."),
  x(8,8,1963,"A track in Buckinghamshire","british","England","The Great Train Robbery. Biggs will be a headline for decades."),
  x(8,9,1974,"A helicopter on a lawn","world","Washington","Nixon. Ford will pardon him."),
  x(8,10,1628,"A harbour in Stockholm","world","Sweden","Vasa. Twenty minutes into a maiden voyage."),
  x(8,11,1965,"A street in Watts","world","Los Angeles","Six days. The long hot summer has a date."),
  x(8,12,1944,"A pipe under the Channel","ww2","Normandy","PLUTO. The advance has a tap."),
  x(8,13,1704,"A village in Bavaria","british","Blenheim","Marlborough. The Sun King’s unbeaten record ends."),
  x(8,14,1947,"A midnight in Karachi","world","Pakistan","The Raj is a day from being two countries."),
  x(8,15,1057,"A field at Lumphanan","british","Scotland","Macbeth. Shakespeare will improve the story."),
  x(8,16,1977,"A bathroom in Graceland","world","Memphis","The King has left the building."),
  x(8,17,1982,"A silver disc in Germany","world","Europe","The compact disc. The cassette should be worried."),
  x(8,18,1587,"A child on Roanoke","world","Carolina","Virginia Dare. The colony will vanish."),
  x(8,19,1692,"More hangings in Salem","world","Massachusetts","The panic is not done."),
  x(8,20,917,"A fortress on the Duero","world","Spain","The Reconquista, a long attrition."),
  x(8,21,1808,"A ridge in Portugal","british","Vimeiro","Wellesley, not yet Wellington."),
  x(8,22,1849,"Venice surrenders","world","Adriatic","The republic of St Mark, Austrian again. Manin has lost."),
  x(8,23,1305,"A scaffold at Smithfield","british","London","Wallace. Scotland has a martyr."),
  x(8,24,1572,"A signal in Paris","world","France","St Bartholomew. A wedding, then a massacre."),
  x(8,25,1830,"An opera in Brussels","world","Belgium","A riot. A country is about to be sung into existence."),
  x(8,26,1920,"A certification in Washington","world","United States","The 19th Amendment. Tennessee was the last state needed."),
  x(8,27,1979,"A boat in Mullaghmore","british","Ireland","Mountbatten. A war that is not called a war."),
  x(8,28,476,"A boy in Ravenna","romans","Italy","Romulus Augustulus. The kit is sent east."),
  x(8,29,1949,"A cloud in Kazakhstan","world","USSR","Joe-1. The monopoly is over."),
  x(8,30,1862,"A field in Virginia","civil-war","Manassas","Second Bull Run ends. The road to Antietam is open."),
  x(8,31,1422,"A castle at Vincennes","british","France","Henry V. Dysentery, not Agincourt. The baby inherits a war."),
  x(9,1,1715,"A bed at Versailles","world","France","The Sun King goes out. Europe can blink."),
  x(9,2,31,"A cape in Greece","romans","Actium","Octavian. The last civil war of the Republic is a naval battle."),
  x(9,3,1658,"A storm over Whitehall","civil-war","London","Cromwell dies. The Protectorate has a year."),
  x(9,4,1998,"A garage in California","world","United States","Google. The world’s librarian is a search box."),
  x(9,5,1698,"A tax on beards","world","Russia","Peter. Modernisation at scissor-point."),
  x(9,6,1914,"A river in France","ww2","Marne","Taxis from Paris. The Schlieffen Plan dies."),
  x(9,7,1812,"A village west of Moscow","world","Borodino","A meat grinder. Kutuzov withdraws."),
  x(9,8,1888,"Twelve clubs","british","England","The Football League. The working week acquires a religion."),
  x(9,9,1776,"A new name in Philadelphia","world","United States","United States, not United Colonies. Branding."),
  x(9,10,1977,"A machine in Marseille","world","France","The last guillotine. It is retired."),
  x(9,11,1297,"A bridge near Stirling","british","Scotland","Wallace. The schiltron works."),
  x(9,12,1940,"A hole in a hill","world","France","Lascaux. Four boys and a dog."),
  x(9,13,1993,"A lawn in Washington","world","United States","Oslo, as a handshake."),
  x(9,14,1812,"An empty city","world","Moscow","Napoleon enters. Then the fires."),
  x(9,15,1830,"A track in Lancashire","british","England","Huskisson. The railway age’s first VIP casualty."),
  x(9,16,1810,"A bell in Dolores","world","Mexico","A priest. A war of independence."),
  x(9,17,1939,"A second invasion of Poland","ww2","East","The secret protocol, enacted."),
  x(9,18,1931,"A railway in Manchuria","world","China","Mukden. Japan’s pretext."),
  x(9,19,1870,"A ring around Paris","world","France","The siege. Balloons, rats, a republic in a scrape."),
  x(9,20,1792,"A mill at Valmy","world","France","The Revolution’s army holds. Goethe is watching."),
  x(9,21,1937,"A hole in the ground","british","London","The Hobbit. Tolkien has a sequel in him."),
  x(9,22,1980,"A river called Shatt","world","Gulf","Iraq into Iran. Eight years."),
  x(9,23,1846,"A calculation in Berlin","world","Germany","Neptune. Found with maths before a telescope."),
  x(9,24,1960,"A hull in Virginia","world","United States","Enterprise. A carrier with a reactor."),
  x(9,25,1396,"A crusade on the Danube","world","Nicopolis","Chivalry has a bad day."),
  x(9,26,1960,"A studio in Chicago","world","United States","Kennedy, Nixon, television. Makeup is half the history."),
  x(9,27,1540,"A bull in Rome","world","Italy","The Jesuits. The Counter-Reformation’s most effective order."),
  x(9,28,1928,"A messy dish in London","british","England","Penicillin. Accident, then a civilisation."),
  x(9,29,1916,"A number on a ledger","world","United States","Rockefeller, a billion. The first of the species."),
  x(9,30,1399,"A hall at Westminster","british","England","Richard II. Bolingbroke has the job."),
  x(10,1,1890,"A valley fenced","world","California","Yosemite. The national park as a brand."),
  x(10,2,1869,"A birth in Porbandar","world","India","Gandhi. An empire’s most successful opponent."),
  x(10,3,1226,"A death in Assisi","world","Italy","Francis. The order will be less poor."),
  x(10,4,1535,"A Bible in English","tudors","Antwerp / London","Coverdale. The whole thing, in the vernacular."),
  x(10,5,1789,"A march of women","world","Versailles","Bread, and the queen. The family will be in Paris by morning."),
  x(10,6,1927,"A screen with sound","world","New York","The Jazz Singer. Silent Hollywood has a year or two."),
  x(10,7,1763,"A line on a map","british","America","The Proclamation. Colonists will ignore it."),
  x(10,8,1952,"A fog in Harrow","british","London","112 dead. Britain’s worst peacetime rail crash."),
  x(10,9,1000,"A shore in Vinland","world","Newfoundland","Leif. America, five centuries early."),
  x(10,10,1913,"A dike at Gamboa","world","Panama","The last gap. The oceans are about to shake hands."),
  x(10,11,1899,"A telegram in Africa","british","South Africa","The Second Boer War. Khaki, camps, a longer empire."),
  x(10,12,1915,"A wall in Brussels","ww2","Belgium","Cavell. Recruitment posters write themselves."),
  x(10,13,1792,"A stone in a swamp","world","Washington","The White House cornerstone. It will burn in 1814."),
  x(10,14,1964,"A prize in Oslo","world","Norway","King, thirty-five. The movement has a medal."),
  x(10,15,1964,"A holiday in Sochi","world","USSR","Khrushchev comes home to a different job."),
  x(10,16,1934,"A column walking west","world","China","The Long March. The CCP’s founding epic."),
  x(10,17,1346,"A field at Durham","british","England","Neville’s Cross. A Scottish king in the Tower."),
  x(10,18,1922,"A company in London","british","England","The BBC. The voice of the nation, eventually."),
  x(10,19,1987,"Screens in red","world","New York","Black Monday. 22 percent."),
  x(10,20,1973,"A roof like sails","world","Sydney","The Opera House. Late, over budget, unmistakable."),
  x(10,21,1966,"A tip above a school","british","Wales","Aberfan. 116 children."),
  x(10,22,1797,"A jump from a balloon","world","Paris","Garnerin. The landing is not elegant."),
  x(10,23,1942,"A ridge in Egypt","ww2","Alamein","Montgomery’s set-piece. The desert war is about to turn."),
  x(10,24,1945,"A charter in force","world","United Nations","The Security Council has a job it will not always do."),
  x(10,25,1971,"A vote in New York","world","United Nations","Beijing takes the seat. Taipei becomes a controversy."),
  x(10,26,1881,"Thirty seconds in Tombstone","world","Arizona","The O.K. Corral. Wyatt Earp’s brand is made."),
  x(10,27,1978,"A Pole in white","world","Rome","John Paul II. The Iron Curtain has a problem."),
  x(10,28,1940,"A word in Athens","ww2","Greece","Oxi. The mountains will embarrass Mussolini."),
  x(10,29,1618,"A block at Westminster","british","London","Raleigh. The New World man dies in the Old."),
  x(10,30,1485,"A crown that looks official","tudors","Westminster","Henry VII. Bosworth was five weeks ago."),
  x(10,31,1926,"A hospital in Detroit","world","United States","Houdini. The magician does not come back."),
  x(11,1,1922,"A sultan leaves","world","Turkey","The Ottoman throne, empty. The caliphate has a year."),
  x(11,2,1960,"A jury in London","british","England","Lady Chatterley. The sixties, in a courtroom."),
  x(11,3,1957,"A dog in a sphere","world","Orbit","Laika. She will not come home."),
  x(11,4,1956,"Tanks in Pest","world","Hungary","The revolution is over. Kádár will last decades."),
  x(11,5,1911,"A war for Tripoli","world","Libya","Italy and the Ottomans. Airplanes will bomb, as a method."),
  x(11,6,1429,"A child at Westminster","british","England","Henry VI. France will have to wait."),
  x(11,7,1918,"A rumour on the front","ww2","France","The false armistice. Men still die."),
  x(11,8,1602,"A library that will not lend","british","Oxford","The Bodleian. Scholars must come to the books."),
  x(11,9,1799,"A coup in a greenhouse","world","Paris","Brumaire. The Revolution, Napoleon says, is over."),
  x(11,10,1483,"A birth in Eisleben","world","Germany","Luther. Still an infant."),
  x(11,11,1620,"A ship still at anchor","world","Cape Cod","The Compact is signed. The winter is coming."),
  x(11,12,1912,"A tent on the ice","british","Antarctica","Scott’s party, found. The race was already lost."),
  x(11,13,1985,"A town called Armero","world","Colombia","A lahar. The warning was given."),
  x(11,14,1851,"A whale in two volumes","world","New York","Moby-Dick. It will take decades to be understood."),
  x(11,15,1315,"A pass in the Alps","british","Switzerland","Morgarten. Knights discover mountains."),
  x(11,16,1849,"A square in St Petersburg","world","Russia","Dostoevsky. The firing squad is stopped."),
  x(11,17,1989,"A street in Prague","world","Czechoslovakia","Students. The government has weeks."),
  x(11,18,1928,"A mouse with sound","world","New York","Steamboat Willie. A corporation’s mascot."),
  x(11,19,1942,"A code named Uranus","ww2","Stalingrad","The counter-attack. Paulus is about to be encircled."),
  x(11,20,1947,"Austerity at the Abbey","british","London","Elizabeth and Philip. The second Elizabethan age is still five years away."),
  x(11,21,1916,"A bed in Schönbrunn","world","Vienna","Franz Joseph. Sixty-eight years. The Dual Monarchy has two."),
  x(11,22,1718,"A boarding in the Carolina sounds","world","America","Blackbeard. The head on a bowsprit."),
  x(11,23,1940,"A signature in Bucharest","ww2","Romania","The Axis. The oil fields matter more than the alliance."),
  x(11,24,1963,"A garage in Dallas","world","United States","Ruby. Live television. The conspiracy industry is born."),
  x(11,25,1975,"A flag in Paramaribo","world","Suriname","Independence from the Netherlands."),
  x(11,26,1863,"A Thursday named","world","United States","Thanksgiving, as a national date. Lincoln’s war holiday."),
  x(11,27,1895,"A will in Paris","world","France","Nobel. Dynamite’s fortune becomes prizes."),
  x(11,28,1943,"A room in Tehran","ww2","Iran","The Big Three. Overlord gets a date."),
  x(11,29,1781,"A ship called Zong","british","Atlantic","Thrown overboard, for insurance. The case will disgust a generation."),
  x(11,30,1995,"A visit in Belfast","british","Northern Ireland","Clinton. The handshake process. Good Friday is still thirty months away."),
  x(12,1,1640,"A restoration in Lisbon","world","Portugal","Spain loses a crown. João IV."),
  x(12,2,1859,"A scaffold in Virginia","world","United States","John Brown. A martyr before the battle."),
  x(12,3,1967,"A theatre in Cape Town","world","South Africa","Barnard. A heart, eighteen days, a future."),
  x(12,4,1872,"A brigantine found empty","world","Atlantic","Mary Celeste. The sea’s favourite ghost story."),
  x(12,5,1484,"A bull against witches","world","Rome","Innocent VIII. The hunts have a wind."),
  x(12,6,1921,"A table in London","british","England","The Anglo-Irish Treaty. The Civil War is in the post."),
  x(12,7,43,"A road in Italy","romans","Formia","Cicero. The Republic’s greatest voice, silenced."),
  x(12,8,1980,"A doorway on 72nd Street","world","New York","Lennon. The sixties’ last Beatle in New York."),
  x(12,9,1824,"A high field in Peru","world","Ayacucho","Spanish America, the last great field."),
  x(12,10,1898,"A treaty in Paris","world","France","Spain loses an empire. The US acquires one."),
  x(12,11,1816,"A star on a flag","world","United States","Indiana. The Old Northwest filling in."),
  x(12,12,1901,"A letter S in Morse","world","Cornwall / Newfoundland","Marconi. The Atlantic is a wire of air."),
  x(12,13,1642,"A coast of islands","world","New Zealand","Tasman. Māori meet him with canoes and a fight."),
  x(12,14,1861,"A blue room at Windsor","british","England","Albert. Victoria will wear black for forty years."),
  x(12,15,1890,"A cabin on a reservation","world","Dakota","Sitting Bull. Wounded Knee is two weeks away."),
  x(12,16,1653,"A single person in charge","civil-war","Westminster","Cromwell, Lord Protector. A republic with a familiar shape."),
  x(12,17,1538,"A bull against Henry","tudors","Rome","The break is no longer a domestic argument."),
  x(12,18,1865,"A certification in Washington","civil-war","United States","The 13th Amendment. Slavery’s constitutional death."),
  x(12,19,1984,"A signature in Beijing","british","China","Hong Kong, 1997. Two systems, on paper."),
  x(12,20,1606,"Three ships in the Thames","british","London","The Virginia Company. Jamestown is a winter away."),
  x(12,21,1988,"A town in Scotland","british","Lockerbie","A Pan Am jumbo. A Wednesday night."),
  x(12,22,1894,"A verdict in Paris","world","France","Dreyfus. Zola is four years from the front page."),
  x(12,23,1948,"A gallows in Tokyo","ww2","Japan","Tojo. The other Nuremberg."),
  x(12,24,1979,"A column into Kabul","world","Afghanistan","Christmas. The USSR’s last decade has a wound."),
  x(12,25,800,"A surprise in St Peter’s","world","Rome","Charlemagne. The West has an emperor again, of a sort."),
  x(12,26,1791,"An act for two Canadas","british","Westminster","Upper and Lower. 1867 will tidy the names."),
  x(12,27,1945,"Articles in force","world","Washington","The IMF and the Bank. Bretton Woods, operational."),
  x(12,28,1895,"A café in Paris","world","France","The Lumières. A train, a garden, a stunned room."),
  x(12,29,1890,"A creek in the snow","world","South Dakota","Wounded Knee. A Ghost Dance, a disgrace."),
  x(12,30,1916,"A palace on the Moika","world","Petrograd","Rasputin. Poison, bullets, a river. Fourteen months."),
  x(12,31,1600,"A charter in London","british","England","The East India Company. Elizabeth’s last December. The empire has a joint-stock company."),
];
